// Achievement data (100-achievement expansion, part 1) for Karaoke ZERO —
// pure data, no logic.
//
// Split out of achievements.ts (R3 refactor): the performance-oriented
// expansion blocks — "Extended Performance" and "Cumulative Note Grinders".
// Part 2 (progression/daily/social/specials) lives in
// achievement-definitions-expansion-progression.ts; achievement-definitions.ts
// merges all parts into ACHIEVEMENT_DEFINITIONS (exact original order).

import type { AchievementDefinition } from './achievement-definitions';

export const ACHIEVEMENT_DEFINITIONS_EXPANSION_PERFORMANCE: AchievementDefinition[] = [
  // ── 100-Achievement Expansion: Extended Performance ──
  {
    id: 'score_9800',
    name: 'Ultra Star',
    nameKey: 'achievements.score9800.name',
    description: 'Score over 9,800 points',
    descriptionKey: 'achievements.score9800.description',
    icon: '⭐',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'score', value: 9800 },
    reward: { xp: 400 },
  },
  {
    id: 'score_9900',
    name: 'Beyond Perfection',
    nameKey: 'achievements.score9900.name',
    description: 'Score over 9,900 points',
    descriptionKey: 'achievements.score9900.description',
    icon: '🌟',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'score', value: 9900 },
    reward: { xp: 800, title: 'Beyond Perfection', titleKey: 'achievements.score9900.rewardTitle' },
  },
  {
    id: 'combo_300',
    name: 'Combo Titan',
    nameKey: 'achievements.combo300.name',
    description: 'Achieve a 300 note combo',
    descriptionKey: 'achievements.combo300.description',
    icon: '🗿',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'combo', value: 300 },
    reward: { xp: 400 },
  },
  {
    id: 'combo_500',
    name: 'Combo Immortal',
    nameKey: 'achievements.combo500.name',
    description: 'Achieve a 500 note combo',
    descriptionKey: 'achievements.combo500.description',
    icon: '🌋',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'combo', value: 500 },
    reward: { xp: 800, title: 'Combo Immortal', titleKey: 'achievements.combo500.rewardTitle' },
  },
  {
    id: 'accuracy_92',
    name: 'Fine Tuning',
    nameKey: 'achievements.accuracy92.name',
    description: 'Get over 92% accuracy',
    descriptionKey: 'achievements.accuracy92.description',
    icon: '🎚️',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'accuracy', value: 92 },
    reward: { xp: 100 },
  },
  {
    id: 'accuracy_94',
    name: 'Studio Quality',
    nameKey: 'achievements.accuracy94.name',
    description: 'Get over 94% accuracy',
    descriptionKey: 'achievements.accuracy94.description',
    icon: '🎼',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'accuracy', value: 94 },
    reward: { xp: 150 },
  },
  {
    id: 'accuracy_96',
    name: 'Sharpshooter',
    nameKey: 'achievements.accuracy96.name',
    description: 'Get over 96% accuracy',
    descriptionKey: 'achievements.accuracy96.description',
    icon: '🎯',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'accuracy', value: 96 },
    reward: { xp: 300 },
  },
  {
    id: 'accuracy_97',
    name: 'Laser Precision',
    nameKey: 'achievements.accuracy97.name',
    description: 'Get over 97% accuracy',
    descriptionKey: 'achievements.accuracy97.description',
    icon: '🔬',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'accuracy', value: 97 },
    reward: { xp: 450 },
  },
  {
    id: 'accuracy_98',
    name: 'Virtuoso',
    nameKey: 'achievements.accuracy98.name',
    description: 'Get over 98% accuracy',
    descriptionKey: 'achievements.accuracy98.description',
    icon: '🎻',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'accuracy', value: 98 },
    reward: { xp: 600 },
  },
  {
    id: 'perfect_75',
    name: 'Perfect Seventy-Five',
    nameKey: 'achievements.perfect75.name',
    description: 'Get 75 perfect notes in a single song',
    descriptionKey: 'achievements.perfect75.description',
    icon: '💠',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'perfect', value: 75 },
    reward: { xp: 200 },
  },
  {
    id: 'perfect_100',
    name: 'Perfect Century',
    nameKey: 'achievements.perfect100.name',
    description: 'Get 100 perfect notes in a single song',
    descriptionKey: 'achievements.perfect100.description',
    icon: '💯',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'perfect', value: 100 },
    reward: { xp: 350 },
  },
  {
    id: 'perfect_150',
    name: 'Perfect Storm',
    nameKey: 'achievements.perfect150.name',
    description: 'Get 150 perfect notes in a single song',
    descriptionKey: 'achievements.perfect150.description',
    icon: '🌪️',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'perfect', value: 150 },
    reward: { xp: 600 },
  },
  {
    id: 'golden_30',
    name: 'Golden Tide',
    nameKey: 'achievements.golden30.name',
    description: 'Hit 30 golden notes in a single song',
    descriptionKey: 'achievements.golden30.description',
    icon: '🌊',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'golden', value: 30 },
    reward: { xp: 200 },
  },
  {
    id: 'golden_40',
    name: 'Golden Symphony',
    nameKey: 'achievements.golden40.name',
    description: 'Hit 40 golden notes in a single song',
    descriptionKey: 'achievements.golden40.description',
    icon: '🎹',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'golden', value: 40 },
    reward: { xp: 350 },
  },

  // ── 100-Achievement Expansion: Cumulative Note Grinders ──
  {
    id: 'perfect_500',
    name: 'Perfect Machine',
    nameKey: 'achievements.perfect500.name',
    description: 'Hit 500 perfect notes in total',
    descriptionKey: 'achievements.perfect500.description',
    icon: '🤖',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'perfect', value: 500, cumulative: true },
    reward: { xp: 250 },
  },
  {
    id: 'perfect_1000',
    name: 'Precision Powerhouse',
    nameKey: 'achievements.perfect1000.name',
    description: 'Hit 1,000 perfect notes in total',
    descriptionKey: 'achievements.perfect1000.description',
    icon: '⚙️',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'perfect', value: 1000, cumulative: true },
    reward: { xp: 500 },
  },
  {
    id: 'perfect_5000',
    name: 'Perfect Avalanche',
    nameKey: 'achievements.perfect5000.name',
    description: 'Hit 5,000 perfect notes in total',
    descriptionKey: 'achievements.perfect5000.description',
    icon: '🏔️',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'perfect', value: 5000, cumulative: true },
    reward: { xp: 1500 },
  },
  {
    id: 'perfect_10000',
    name: 'Perfect Ten Thousand',
    nameKey: 'achievements.perfect10000.name',
    description: 'Hit 10,000 perfect notes in total',
    descriptionKey: 'achievements.perfect10000.description',
    icon: '🌌',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'perfect', value: 10000, cumulative: true },
    reward: { xp: 4000, title: 'Perfect Ten Thousand', titleKey: 'achievements.perfect10000.rewardTitle' },
  },
  {
    id: 'golden_250',
    name: 'Golden Harvest',
    nameKey: 'achievements.golden250.name',
    description: 'Hit 250 golden notes in total',
    descriptionKey: 'achievements.golden250.description',
    icon: '🌾',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'golden', value: 250, cumulative: true },
    reward: { xp: 500 },
  },
  {
    id: 'golden_1000',
    name: 'Golden Downpour',
    nameKey: 'achievements.golden1000.name',
    description: 'Hit 1,000 golden notes in total',
    descriptionKey: 'achievements.golden1000.description',
    icon: '🌧️',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'golden', value: 1000, cumulative: true },
    reward: { xp: 1500 },
  },
  {
    id: 'golden_5000',
    name: 'Midas Voice',
    nameKey: 'achievements.golden5000.name',
    description: 'Hit 5,000 golden notes in total',
    descriptionKey: 'achievements.golden5000.description',
    icon: '🥇',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'golden', value: 5000, cumulative: true },
    reward: { xp: 4000, title: 'Midas Voice', titleKey: 'achievements.golden5000.rewardTitle' },
  },

];
