// Achievement data (100-achievement expansion, part 2) for Karaoke ZERO —
// pure data, no logic.
//
// Split out of achievements.ts (R3 refactor): the long-tail expansion blocks
// — "Long-Term Progression", "Daily & Weekly Grinders", "Social Grinders"
// and "Specials & Variety". Part 1 (performance/grinders) lives in
// achievement-definitions-expansion-performance.ts; achievement-definitions.ts
// merges all parts into ACHIEVEMENT_DEFINITIONS (exact original order).

import type { AchievementDefinition } from './achievement-definitions';

export const ACHIEVEMENT_DEFINITIONS_EXPANSION_PROGRESSION: AchievementDefinition[] = [
  // ── 100-Achievement Expansion: Long-Term Progression ──
  {
    id: 'songs_250',
    name: 'Songbook Veteran',
    nameKey: 'achievements.songs250.name',
    description: 'Complete 250 songs',
    descriptionKey: 'achievements.songs250.description',
    icon: '📚',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'songs', value: 250, cumulative: true },
    reward: { xp: 750 },
  },
  {
    id: 'songs_500',
    name: 'Half-Thousand Club',
    nameKey: 'achievements.songs500.name',
    description: 'Complete 500 songs',
    descriptionKey: 'achievements.songs500.description',
    icon: '🎖️',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'songs', value: 500, cumulative: true },
    reward: { xp: 1500 },
  },
  {
    id: 'songs_1000',
    name: 'Thousand-Song Legend',
    nameKey: 'achievements.songs1000.name',
    description: 'Complete 1,000 songs',
    descriptionKey: 'achievements.songs1000.description',
    icon: '🏆',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'songs', value: 1000, cumulative: true },
    reward: { xp: 5000, title: 'Thousand-Song Legend', titleKey: 'achievements.songs1000.rewardTitle' },
  },
  {
    id: 'games_50',
    name: 'Frequent Singer',
    nameKey: 'achievements.games50.name',
    description: 'Play 50 games',
    descriptionKey: 'achievements.games50.description',
    icon: '🕹️',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'games', value: 50, cumulative: true },
    reward: { xp: 200 },
  },
  {
    id: 'games_100',
    name: 'Century Club',
    nameKey: 'achievements.games100.name',
    description: 'Play 100 games',
    descriptionKey: 'achievements.games100.description',
    icon: '💯',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'games', value: 100, cumulative: true },
    reward: { xp: 500 },
  },
  {
    id: 'games_250',
    name: 'Arcade Regular',
    nameKey: 'achievements.games250.name',
    description: 'Play 250 games',
    descriptionKey: 'achievements.games250.description',
    icon: '🎡',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'games', value: 250, cumulative: true },
    reward: { xp: 1250 },
  },
  {
    id: 'games_500',
    name: 'Marathon Maniac',
    nameKey: 'achievements.games500.name',
    description: 'Play 500 games',
    descriptionKey: 'achievements.games500.description',
    icon: '🚀',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'games', value: 500, cumulative: true },
    reward: { xp: 3000, title: 'Marathon Maniac', titleKey: 'achievements.games500.rewardTitle' },
  },
  {
    id: 'level_25',
    name: 'Seasoned Singer',
    nameKey: 'achievements.level25.name',
    description: 'Reach level 25',
    descriptionKey: 'achievements.level25.description',
    icon: '📈',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'level', value: 25 },
    reward: { xp: 500 },
  },
  {
    id: 'level_50',
    name: 'Elite Vocalist',
    nameKey: 'achievements.level50.name',
    description: 'Reach level 50',
    descriptionKey: 'achievements.level50.description',
    icon: '🎗️',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'level', value: 50 },
    reward: { xp: 1500, title: 'Elite Vocalist', titleKey: 'achievements.level50.rewardTitle' },
  },
  {
    id: 'level_100',
    name: 'Level 100 Legend',
    nameKey: 'achievements.level100.name',
    description: 'Reach level 100',
    descriptionKey: 'achievements.level100.description',
    icon: '👑',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'level', value: 100 },
    reward: { xp: 5000, title: 'Level 100 Legend', titleKey: 'achievements.level100.rewardTitle' },
  },

  // ── 100-Achievement Expansion: Daily & Weekly Grinders ──
  {
    id: 'daily_100',
    name: 'Daily Centurion',
    nameKey: 'achievements.daily100.name',
    description: 'Complete 100 daily challenges',
    descriptionKey: 'achievements.daily100.description',
    icon: '🏅',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'daily', value: 100 },
    reward: { xp: 1500 },
  },
  {
    id: 'daily_250',
    name: 'Daily Diehard',
    nameKey: 'achievements.daily250.name',
    description: 'Complete 250 daily challenges',
    descriptionKey: 'achievements.daily250.description',
    icon: '🔁',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'daily', value: 250 },
    reward: { xp: 3000 },
  },
  {
    id: 'daily_500',
    name: 'Daily Immortal',
    nameKey: 'achievements.daily500.name',
    description: 'Complete 500 daily challenges',
    descriptionKey: 'achievements.daily500.description',
    icon: '⏳',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'daily', value: 500 },
    reward: { xp: 5000, title: 'Daily Immortal', titleKey: 'achievements.daily500.rewardTitle' },
  },
  {
    id: 'streak_60',
    name: 'Iron Will',
    nameKey: 'achievements.streak60.name',
    description: 'Keep a 60-day daily streak',
    descriptionKey: 'achievements.streak60.description',
    icon: '🛡️',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'bestStreak', value: 60 },
    reward: { xp: 1000 },
  },
  {
    id: 'streak_100',
    name: 'Hundred-Day Hero',
    nameKey: 'achievements.streak100.name',
    description: 'Keep a 100-day daily streak',
    descriptionKey: 'achievements.streak100.description',
    icon: '⏰',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'bestStreak', value: 100 },
    reward: { xp: 2000 },
  },
  {
    id: 'streak_180',
    name: 'Half-Year Devotion',
    nameKey: 'achievements.streak180.name',
    description: 'Keep a 180-day daily streak',
    descriptionKey: 'achievements.streak180.description',
    icon: '🗓️',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'bestStreak', value: 180 },
    reward: { xp: 3500, title: 'Half-Year Devotion', titleKey: 'achievements.streak180.rewardTitle' },
  },
  {
    id: 'streak_365',
    name: 'Yearly Legend',
    nameKey: 'achievements.streak365.name',
    description: 'Keep a 365-day daily streak',
    descriptionKey: 'achievements.streak365.description',
    icon: '🎆',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'bestStreak', value: 365 },
    reward: { xp: 7500, title: 'Yearly Legend', titleKey: 'achievements.streak365.rewardTitle' },
  },
  {
    id: 'weekly_15',
    name: 'Weekly Stalwart',
    nameKey: 'achievements.weekly15.name',
    description: 'Complete 15 weekly challenges',
    descriptionKey: 'achievements.weekly15.description',
    icon: '📘',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'weekly', value: 15 },
    reward: { xp: 500 },
  },
  {
    id: 'weekly_30',
    name: 'Weekly Pillar',
    nameKey: 'achievements.weekly30.name',
    description: 'Complete 30 weekly challenges',
    descriptionKey: 'achievements.weekly30.description',
    icon: '🏛️',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'weekly', value: 30 },
    reward: { xp: 1200 },
  },
  {
    id: 'weekly_52',
    name: 'Year of Weeks',
    nameKey: 'achievements.weekly52.name',
    description: 'Complete 52 weekly challenges',
    descriptionKey: 'achievements.weekly52.description',
    icon: '📆',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'weekly', value: 52 },
    reward: { xp: 3000, title: 'Year of Weeks', titleKey: 'achievements.weekly52.rewardTitle' },
  },
  {
    id: 'encore_10',
    name: 'Encore!',
    nameKey: 'achievements.encore10.name',
    description: 'Play 10 games in a single day',
    descriptionKey: 'achievements.encore10.description',
    icon: '🎤',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'gamesToday', value: 10 },
    reward: { xp: 500 },
  },

  // ── 100-Achievement Expansion: Social Grinders ──
  {
    id: 'duets_25',
    name: 'Duet Devotee',
    nameKey: 'achievements.duets25.name',
    description: 'Sing 25 duets',
    descriptionKey: 'achievements.duets25.description',
    icon: '👯',
    category: 'social',
    rarity: 'rare',
    requirement: { type: 'duet', value: 25 },
    reward: { xp: 400 },
  },
  {
    id: 'duets_50',
    name: 'Dynamic Duo',
    nameKey: 'achievements.duets50.name',
    description: 'Sing 50 duets',
    descriptionKey: 'achievements.duets50.description',
    icon: '👫',
    category: 'social',
    rarity: 'epic',
    requirement: { type: 'duet', value: 50 },
    reward: { xp: 1000 },
  },
  {
    id: 'duets_100',
    name: 'Duet Century',
    nameKey: 'achievements.duets100.name',
    description: 'Sing 100 duets',
    descriptionKey: 'achievements.duets100.description',
    icon: '💞',
    category: 'social',
    rarity: 'legendary',
    requirement: { type: 'duet', value: 100 },
    reward: { xp: 2500, title: 'Duet Century', titleKey: 'achievements.duets100.rewardTitle' },
  },
  {
    id: 'duels_5',
    name: 'Duelist',
    nameKey: 'achievements.duels5.name',
    description: 'Win 5 duels',
    descriptionKey: 'achievements.duels5.description',
    icon: '🤺',
    category: 'social',
    rarity: 'uncommon',
    requirement: { type: 'duelsWon', value: 5 },
    reward: { xp: 150 },
  },
  {
    id: 'duels_10',
    name: 'Duel Master',
    nameKey: 'achievements.duels10.name',
    description: 'Win 10 duels',
    descriptionKey: 'achievements.duels10.description',
    icon: '🥋',
    category: 'social',
    rarity: 'rare',
    requirement: { type: 'duelsWon', value: 10 },
    reward: { xp: 400 },
  },
  {
    id: 'duels_25',
    name: 'Duel Overlord',
    nameKey: 'achievements.duels25.name',
    description: 'Win 25 duels',
    descriptionKey: 'achievements.duels25.description',
    icon: '🐉',
    category: 'social',
    rarity: 'epic',
    requirement: { type: 'duelsWon', value: 25 },
    reward: { xp: 1000, title: 'Duel Overlord', titleKey: 'achievements.duels25.rewardTitle' },
  },
  {
    id: 'party_10',
    name: 'Party Animal',
    nameKey: 'achievements.party10.name',
    description: 'Play 10 party games',
    descriptionKey: 'achievements.party10.description',
    icon: '🎊',
    category: 'social',
    rarity: 'uncommon',
    requirement: { type: 'party', value: 10 },
    reward: { xp: 200 },
  },
  {
    id: 'party_25',
    name: 'Life of the Party',
    nameKey: 'achievements.party25.name',
    description: 'Play 25 party games',
    descriptionKey: 'achievements.party25.description',
    icon: '🥳',
    category: 'social',
    rarity: 'rare',
    requirement: { type: 'party', value: 25 },
    reward: { xp: 500 },
  },
  {
    id: 'party_50',
    name: 'Party Legend',
    nameKey: 'achievements.party50.name',
    description: 'Play 50 party games',
    descriptionKey: 'achievements.party50.description',
    icon: '🍾',
    category: 'social',
    rarity: 'epic',
    requirement: { type: 'party', value: 50 },
    reward: { xp: 1250 },
  },

  // ── 100-Achievement Expansion: Specials & Variety ──
  {
    id: 'disney_25',
    name: 'Disney Enthusiast',
    nameKey: 'achievements.disney25.name',
    description: 'Sing 25 Disney songs',
    descriptionKey: 'achievements.disney25.description',
    icon: '🎠',
    category: 'special',
    rarity: 'rare',
    requirement: { type: 'disney', value: 25 },
    reward: { xp: 500 },
  },
  {
    id: 'disney_50',
    name: 'Once Upon a Song',
    nameKey: 'achievements.disney50.name',
    description: 'Sing 50 Disney songs',
    descriptionKey: 'achievements.disney50.description',
    icon: '🧚',
    category: 'special',
    rarity: 'epic',
    requirement: { type: 'disney', value: 50 },
    reward: { xp: 1200, title: 'Disney Royalty', titleKey: 'achievements.disney50.rewardTitle' },
  },
  {
    id: 'genres_8',
    name: 'Genre Wanderer',
    nameKey: 'achievements.genres8.name',
    description: 'Sing songs from 8 different genres',
    descriptionKey: 'achievements.genres8.description',
    icon: '🧭',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'genre', value: 8 },
    reward: { xp: 150 },
  },
  {
    id: 'genres_10',
    name: 'Genre Aficionado',
    nameKey: 'achievements.genres10.name',
    description: 'Sing songs from 10 different genres',
    descriptionKey: 'achievements.genres10.description',
    icon: '🗺️',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'genre', value: 10 },
    reward: { xp: 350 },
  },
  {
    id: 'clean_sheet',
    name: 'Clean Sheet',
    nameKey: 'achievements.cleanSheet.name',
    description: 'Finish a song with 50+ notes and zero misses',
    descriptionKey: 'achievements.cleanSheet.description',
    icon: '🧼',
    category: 'special',
    rarity: 'epic',
    requirement: { type: 'special', value: 10 },
    reward: { xp: 300 },
  },
  {
    id: 'weekend_singer',
    name: 'Weekend Singer',
    nameKey: 'achievements.weekendSinger.name',
    description: 'Finish a song on Saturday or Sunday',
    descriptionKey: 'achievements.weekendSinger.description',
    icon: '🌴',
    category: 'special',
    rarity: 'common',
    requirement: { type: 'special', value: 11 },
    reward: { xp: 50 },
  },
  {
    id: 'lunch_break',
    name: 'Lunch Break',
    nameKey: 'achievements.lunchBreak.name',
    description: 'Finish a song between 12 and 2 PM',
    descriptionKey: 'achievements.lunchBreak.description',
    icon: '🥪',
    category: 'special',
    rarity: 'common',
    requirement: { type: 'special', value: 12 },
    reward: { xp: 50 },
  },
];
