// Achievement data (base set) for Karaoke ZERO — pure data, no logic.
//
// Split out of achievements.ts (R3 refactor): the base achievement set as it
// grew over the user-feedback rounds — performance, progression, social,
// special, daily & weekly challenge, extended performance and social &
// variety achievements. The 100-achievement expansion lives in
// achievement-definitions-expansion-*.ts; achievement-definitions.ts merges
// all parts into ACHIEVEMENT_DEFINITIONS (exact original order).

import type { AchievementDefinition } from './achievement-definitions';

export const ACHIEVEMENT_DEFINITIONS_CORE: AchievementDefinition[] = [
  // Performance Achievements
  {
    id: 'first_note',
    name: 'First Note',
    nameKey: 'achievements.firstNote.name',
    description: 'Hit your first note',
    descriptionKey: 'achievements.firstNote.description',
    icon: '🎵',
    category: 'performance',
    rarity: 'common',
    requirement: { type: 'perfect', value: 1, cumulative: true },
    reward: { xp: 10 },
  },
  {
    id: 'perfect_ten',
    name: 'Perfect Ten',
    nameKey: 'achievements.perfectTen.name',
    description: 'Get 10 Perfect hits in a single song',
    descriptionKey: 'achievements.perfectTen.description',
    icon: '✨',
    category: 'performance',
    rarity: 'common',
    requirement: { type: 'perfect', value: 10 },
    reward: { xp: 25 },
  },
  {
    id: 'combo_master',
    name: 'Combo Master',
    nameKey: 'achievements.comboMaster.name',
    description: 'Achieve a 50 note combo',
    descriptionKey: 'achievements.comboMaster.description',
    icon: '🔥',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'combo', value: 50 },
    reward: { xp: 50 },
  },
  {
    id: 'combo_king',
    name: 'Combo King',
    nameKey: 'achievements.comboKing.name',
    description: 'Achieve a 100 note combo',
    descriptionKey: 'achievements.comboKing.description',
    icon: '👑',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'combo', value: 100 },
    reward: { xp: 100, title: 'Combo King', titleKey: 'achievements.comboKing.rewardTitle' },
  },
  {
    id: 'combo_legend',
    name: 'Combo Legend',
    nameKey: 'achievements.comboLegend.name',
    description: 'Achieve a 200 note combo',
    descriptionKey: 'achievements.comboLegend.description',
    icon: '🌟',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'combo', value: 200 },
    reward: { xp: 250, title: 'Combo Legend', titleKey: 'achievements.comboLegend.rewardTitle' },
  },
  {
    id: 'perfect_song',
    name: 'Perfect Song',
    nameKey: 'achievements.perfectSong.name',
    description: 'Get 99.5%+ accuracy on a song',
    descriptionKey: 'achievements.perfectSong.description',
    icon: '💎',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'accuracy', value: 99.5 },
    reward: { xp: 500, title: 'Perfectionist', titleKey: 'achievements.perfectSong.rewardTitle' },
  },
  {
    id: 'accuracy_90',
    name: 'Pitch Perfect',
    nameKey: 'achievements.pitchPerfect.name',
    description: 'Get over 90% accuracy',
    descriptionKey: 'achievements.pitchPerfect.description',
    icon: '🎯',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'accuracy', value: 90 },
    reward: { xp: 75 },
  },
  {
    id: 'score_8k',
    name: 'Rising Star',
    nameKey: 'achievements.risingStar.name',
    description: 'Score over 8,000 points',
    descriptionKey: 'achievements.risingStar.description',
    icon: '⭐',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'score', value: 8000 },
    reward: { xp: 50 },
  },
  {
    id: 'score_9k',
    name: 'Score Master',
    nameKey: 'achievements.scoreMaster.name',
    description: 'Score over 9,000 points',
    descriptionKey: 'achievements.scoreMaster.description',
    icon: '🏆',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'score', value: 9000 },
    reward: { xp: 150 },
  },
  {
    id: 'score_9500',
    name: 'Flawless',
    nameKey: 'achievements.flawless.name',
    description: 'Score over 9,500 points',
    descriptionKey: 'achievements.flawless.description',
    icon: '💎',
    category: 'performance',
    rarity: 'legendary',
    requirement: { type: 'score', value: 9500 },
    reward: { xp: 300, title: 'Flawless', titleKey: 'achievements.flawless.rewardTitle' },
  },
  {
    id: 'golden_collector',
    name: 'Golden Collector',
    nameKey: 'achievements.goldenCollector.name',
    description: 'Hit 10 golden notes',
    descriptionKey: 'achievements.goldenCollector.description',
    icon: '⭐',
    category: 'performance',
    rarity: 'uncommon',
    requirement: { type: 'golden', value: 10, cumulative: true },
    reward: { xp: 30 },
  },
  {
    id: 'golden_master',
    name: 'Golden Master',
    nameKey: 'achievements.goldenMaster.name',
    description: 'Hit 50 golden notes',
    descriptionKey: 'achievements.goldenMaster.description',
    icon: '🌟',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'golden', value: 50, cumulative: true },
    reward: { xp: 100, title: 'Golden Voice', titleKey: 'achievements.goldenMaster.rewardTitle' },
  },

  // Progression Achievements
  {
    id: 'first_song',
    name: 'First Steps',
    nameKey: 'achievements.firstSong.name',
    description: 'Complete your first song',
    descriptionKey: 'achievements.firstSong.description',
    icon: '🎤',
    category: 'progression',
    rarity: 'common',
    requirement: { type: 'songs', value: 1, cumulative: true },
    reward: { xp: 20 },
  },
  {
    id: 'ten_songs',
    name: 'Karaoke Enthusiast',
    nameKey: 'achievements.karaokeEnthusiast.name',
    description: 'Complete 10 songs',
    descriptionKey: 'achievements.karaokeEnthusiast.description',
    icon: '🎶',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'songs', value: 10, cumulative: true },
    reward: { xp: 50 },
  },
  {
    id: 'fifty_songs',
    name: 'Karaoke Regular',
    nameKey: 'achievements.karaokeRegular.name',
    description: 'Complete 50 songs',
    descriptionKey: 'achievements.karaokeRegular.description',
    icon: '🎪',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'songs', value: 50, cumulative: true },
    reward: { xp: 150 },
  },
  {
    id: 'hundred_songs',
    name: 'Karaoke Legend',
    nameKey: 'achievements.karaokeLegend.name',
    description: 'Complete 100 songs',
    descriptionKey: 'achievements.karaokeLegend.description',
    icon: '👑',
    category: 'progression',
    rarity: 'legendary',
    requirement: { type: 'songs', value: 100, cumulative: true },
    reward: { xp: 300, title: 'Karaoke Legend', titleKey: 'achievements.karaokeLegend.rewardTitle' },
  },
  {
    id: 'five_games',
    name: 'Getting Started',
    nameKey: 'achievements.gettingStarted.name',
    description: 'Play 5 games',
    descriptionKey: 'achievements.gettingStarted.description',
    icon: '🎮',
    category: 'progression',
    rarity: 'common',
    requirement: { type: 'games', value: 5, cumulative: true },
    reward: { xp: 15 },
  },
  {
    id: 'twenty_games',
    name: 'Dedicated Singer',
    nameKey: 'achievements.dedicatedSinger.name',
    description: 'Play 20 games',
    descriptionKey: 'achievements.dedicatedSinger.description',
    icon: '🎯',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'games', value: 20, cumulative: true },
    reward: { xp: 40 },
  },

  // Social Achievements
  {
    id: 'party_time',
    name: 'Party Time!',
    nameKey: 'achievements.partyTime.name',
    description: 'Play a party game mode',
    descriptionKey: 'achievements.partyTime.description',
    icon: '🎉',
    category: 'social',
    rarity: 'common',
    requirement: { type: 'special', value: 1 },
    reward: { xp: 25 },
  },
  {
    id: 'duel_winner',
    name: 'Duel Champion',
    nameKey: 'achievements.duelChampion.name',
    description: 'Win a duel match',
    descriptionKey: 'achievements.duelChampion.description',
    icon: '⚔️',
    category: 'social',
    rarity: 'uncommon',
    requirement: { type: 'special', value: 2 },
    reward: { xp: 50 },
  },
  {
    id: 'pass_the_mic',
    name: 'Pass the Mic!',
    nameKey: 'achievements.passTheMic.name',
    description: 'Play Pass the Mic mode',
    descriptionKey: 'achievements.passTheMic.description',
    icon: '🎙️',
    category: 'social',
    rarity: 'common',
    requirement: { type: 'special', value: 3 },
    reward: { xp: 20 },
  },

  // Special Achievements
  {
    id: 'shower_singer',
    name: 'Shower Singer',
    nameKey: 'achievements.showerSinger.name',
    description: 'Score less than 20% on a song',
    descriptionKey: 'achievements.showerSinger.description',
    icon: '🚿',
    category: 'special',
    rarity: 'common',
    requirement: { type: 'accuracy', value: 20 },
    reward: { xp: 5, title: 'Shower Singer', titleKey: 'achievements.showerSinger.rewardTitle' },
  },
  {
    id: 'comeback_king',
    name: 'Comeback King',
    nameKey: 'achievements.comebackKing.name',
    description: 'Get a combo of 50+ after missing 10 notes',
    descriptionKey: 'achievements.comebackKing.description',
    icon: '🦸',
    category: 'special',
    rarity: 'rare',
    requirement: { type: 'special', value: 4 },
    reward: { xp: 75 },
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    nameKey: 'achievements.speedDemon.name',
    description: 'Complete a song at 1.5x speed',
    descriptionKey: 'achievements.speedDemon.description',
    icon: '⚡',
    category: 'special',
    rarity: 'rare',
    requirement: { type: 'special', value: 5 },
    reward: { xp: 100 },
  },
  {
    id: 'blind_master',
    name: 'Blind Master',
    nameKey: 'achievements.blindMaster.name',
    description: 'Complete a song in Blind Karaoke mode',
    descriptionKey: 'achievements.blindMaster.description',
    icon: '🎭',
    category: 'special',
    rarity: 'epic',
    requirement: { type: 'special', value: 6 },
    reward: { xp: 150, title: 'Blind Master', titleKey: 'achievements.blindMaster.rewardTitle' },
  },

  // ── Daily & Weekly Challenge Achievements (profile renovation) ──
  {
    id: 'daily_starter',
    name: 'Daily Starter',
    nameKey: 'achievements.dailyStarter.name',
    description: 'Complete your first daily challenge',
    descriptionKey: 'achievements.dailyStarter.description',
    icon: '📅',
    category: 'progression',
    rarity: 'common',
    requirement: { type: 'daily', value: 1 },
    reward: { xp: 20 },
  },
  {
    id: 'daily_regular',
    name: 'Daily Regular',
    nameKey: 'achievements.dailyRegular.name',
    description: 'Complete 10 daily challenges',
    descriptionKey: 'achievements.dailyRegular.description',
    icon: '🗓️',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'daily', value: 10 },
    reward: { xp: 75 },
  },
  {
    id: 'daily_devoted',
    name: 'Daily Devoted',
    nameKey: 'achievements.dailyDevoted.name',
    description: 'Complete 50 daily challenges',
    descriptionKey: 'achievements.dailyDevoted.description',
    icon: '🏅',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'daily', value: 50 },
    reward: { xp: 200 },
  },
  {
    id: 'streak_week',
    name: 'On Fire',
    nameKey: 'achievements.streakWeek.name',
    description: 'Keep a 7-day daily streak',
    descriptionKey: 'achievements.streakWeek.description',
    icon: '🔥',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'streak', value: 7 },
    reward: { xp: 150 },
  },
  {
    id: 'streak_month',
    name: 'Unstoppable',
    nameKey: 'achievements.streakMonth.name',
    description: 'Keep a 30-day daily streak',
    descriptionKey: 'achievements.streakMonth.description',
    icon: '⚡',
    category: 'progression',
    rarity: 'epic',
    requirement: { type: 'streak', value: 30 },
    reward: { xp: 500, title: 'Unstoppable', titleKey: 'achievements.streakMonth.rewardTitle' },
  },
  {
    id: 'weekly_warrior',
    name: 'Weekly Warrior',
    nameKey: 'achievements.weeklyWarrior.name',
    description: 'Complete 5 weekly challenges',
    descriptionKey: 'achievements.weeklyWarrior.description',
    icon: '📆',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'weekly', value: 5 },
    reward: { xp: 150 },
  },

  // ── Extended Performance Achievements ──
  {
    id: 'accuracy_95',
    name: 'Precision Singer',
    nameKey: 'achievements.precisionSinger.name',
    description: 'Get over 95% accuracy',
    descriptionKey: 'achievements.precisionSinger.description',
    icon: '🎯',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'accuracy', value: 95 },
    reward: { xp: 200 },
  },
  {
    id: 'golden_rush',
    name: 'Golden Rush',
    nameKey: 'achievements.goldenRush.name',
    description: 'Hit 20 golden notes in a single song',
    descriptionKey: 'achievements.goldenRush.description',
    icon: '✨',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'golden', value: 20 },
    reward: { xp: 100 },
  },
  {
    id: 'golden_hundred',
    name: 'Golden Centurion',
    nameKey: 'achievements.goldenCenturion.name',
    description: 'Hit 100 golden notes in total',
    descriptionKey: 'achievements.goldenCenturion.description',
    icon: '💫',
    category: 'performance',
    rarity: 'epic',
    requirement: { type: 'golden', value: 100, cumulative: true },
    reward: { xp: 250 },
  },
  {
    id: 'perfect_fifty',
    name: 'Perfect Fifty',
    nameKey: 'achievements.perfectFifty.name',
    description: 'Hit 50 perfect notes in a single song',
    descriptionKey: 'achievements.perfectFifty.description',
    icon: '💎',
    category: 'performance',
    rarity: 'rare',
    requirement: { type: 'perfect', value: 50 },
    reward: { xp: 100 },
  },
  {
    id: 'lightning_lips',
    name: 'Lightning Lips',
    nameKey: 'achievements.lightningLips.name',
    description: 'Complete a song at 2x speed',
    descriptionKey: 'achievements.lightningLips.description',
    icon: '⚡',
    category: 'special',
    rarity: 'epic',
    requirement: { type: 'special', value: 7 },
    reward: { xp: 200 },
  },

  // ── Social & Variety Achievements ──
  {
    id: 'duet_harmony',
    name: 'Perfect Harmony',
    nameKey: 'achievements.perfectHarmony.name',
    description: 'Sing 10 duets',
    descriptionKey: 'achievements.perfectHarmony.description',
    icon: '🤝',
    category: 'social',
    rarity: 'uncommon',
    requirement: { type: 'duet', value: 10 },
    reward: { xp: 75 },
  },
  {
    id: 'genre_explorer',
    name: 'Genre Explorer',
    nameKey: 'achievements.genreExplorer.name',
    description: 'Sing songs from 5 different genres',
    descriptionKey: 'achievements.genreExplorer.description',
    icon: '🌍',
    category: 'progression',
    rarity: 'uncommon',
    requirement: { type: 'genre', value: 5 },
    reward: { xp: 75 },
  },
  {
    id: 'disney_fan',
    name: 'Disney Fan',
    nameKey: 'achievements.disneyFan.name',
    description: 'Sing 10 Disney songs',
    descriptionKey: 'achievements.disneyFan.description',
    icon: '🏰',
    category: 'special',
    rarity: 'uncommon',
    requirement: { type: 'disney', value: 10 },
    reward: { xp: 100 },
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    nameKey: 'achievements.nightOwl.name',
    description: 'Finish a song between midnight and 4 AM',
    descriptionKey: 'achievements.nightOwl.description',
    icon: '🦉',
    category: 'special',
    rarity: 'uncommon',
    requirement: { type: 'special', value: 8 },
    reward: { xp: 50 },
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    nameKey: 'achievements.earlyBird.name',
    description: 'Finish a song before 8 AM',
    descriptionKey: 'achievements.earlyBird.description',
    icon: '🐦',
    category: 'special',
    rarity: 'uncommon',
    requirement: { type: 'special', value: 9 },
    reward: { xp: 50 },
  },
  {
    id: 'marathon_singer',
    name: 'Marathon Singer',
    nameKey: 'achievements.marathonSinger.name',
    description: 'Play 5 games in a single day',
    descriptionKey: 'achievements.marathonSinger.description',
    icon: '🏃',
    category: 'progression',
    rarity: 'rare',
    requirement: { type: 'gamesToday', value: 5 },
    reward: { xp: 150 },
  },

];
