// Daily Challenge — badge definitions
//
// Part of the daily-challenge module (see ./index.ts).

import type { DailyBadge } from './types';

// Badge definitions
export const DAILY_BADGES: Record<string, Omit<DailyBadge, 'unlockedAt'>> = {
  'first-challenge': {
    id: 'first-challenge',
    name: 'First Steps',
    nameKey: 'dailyChallenge.badges.firstChallenge.name',
    icon: '🌟',
    description: 'Complete your first daily challenge',
    descriptionKey: 'dailyChallenge.badges.firstChallenge.description',
  },
  'week-warrior': {
    id: 'week-warrior',
    name: 'Week Warrior',
    nameKey: 'dailyChallenge.badges.weekWarrior.name',
    icon: '🏆',
    description: 'Maintain a 7-day streak',
    descriptionKey: 'dailyChallenge.badges.weekWarrior.description',
  },
  'fortnight-fighter': {
    id: 'fortnight-fighter',
    name: 'Fortnight Fighter',
    nameKey: 'dailyChallenge.badges.fortnightFighter.name',
    icon: '⚔️',
    description: 'Maintain a 14-day streak',
    descriptionKey: 'dailyChallenge.badges.fortnightFighter.description',
  },
  'monthly-master': {
    id: 'monthly-master',
    name: 'Monthly Master',
    nameKey: 'dailyChallenge.badges.monthlyMaster.name',
    icon: '👑',
    description: 'Maintain a 30-day streak',
    descriptionKey: 'dailyChallenge.badges.monthlyMaster.description',
  },
  'top-3': {
    id: 'top-3',
    name: 'Podium Finish',
    nameKey: 'dailyChallenge.badges.podiumFinish.name',
    icon: '🥇',
    description: 'Finish in top 3 of a daily challenge',
    descriptionKey: 'dailyChallenge.badges.podiumFinish.description',
  },
  'champion': {
    id: 'champion',
    name: 'Daily Champion',
    nameKey: 'dailyChallenge.badges.dailyChampion.name',
    icon: '🏅',
    description: 'Win a daily challenge',
    descriptionKey: 'dailyChallenge.badges.dailyChampion.description',
  },
  'dedicated': {
    id: 'dedicated',
    name: 'Dedicated Singer',
    nameKey: 'dailyChallenge.badges.dedicatedSinger.name',
    icon: '🎤',
    description: 'Complete 30 daily challenges',
    descriptionKey: 'dailyChallenge.badges.dedicatedSinger.description',
  },
  'legendary': {
    id: 'legendary',
    name: 'Legendary Status',
    nameKey: 'dailyChallenge.badges.legendaryStatus.name',
    icon: '⭐',
    description: 'Reach 10,000 total XP',
    descriptionKey: 'dailyChallenge.badges.legendaryStatus.description',
  },
  'century-champion': {
    id: 'century-champion',
    name: 'Century Champion',
    nameKey: 'dailyChallenge.badges.centuryChampion.name',
    icon: '💎',
    description: 'Maintain a 100-day streak',
    descriptionKey: 'dailyChallenge.badges.centuryChampion.description',
  },
  'yearly-legend': {
    id: 'yearly-legend',
    name: 'Yearly Legend',
    nameKey: 'dailyChallenge.badges.yearlyLegend.name',
    icon: '🌟',
    description: 'Maintain a 365-day streak',
    descriptionKey: 'dailyChallenge.badges.yearlyLegend.description',
  },
  'daily-bronze': {
    id: 'daily-bronze',
    name: 'Daily Bronze',
    nameKey: 'dailyChallenge.badges.dailyBronze.name',
    icon: '🥉',
    description: 'Complete 1 daily challenge in one day',
    descriptionKey: 'dailyChallenge.badges.dailyBronze.description',
  },
  'daily-silver': {
    id: 'daily-silver',
    name: 'Daily Silver',
    nameKey: 'dailyChallenge.badges.dailySilver.name',
    icon: '🥈',
    description: 'Complete 3 daily challenges in one day',
    descriptionKey: 'dailyChallenge.badges.dailySilver.description',
  },
  'daily-gold': {
    id: 'daily-gold',
    name: 'Daily Gold',
    nameKey: 'dailyChallenge.badges.dailyGold.name',
    icon: '🥇',
    description: 'Complete all 5 daily challenges in one day',
    descriptionKey: 'dailyChallenge.badges.dailyGold.description',
  },
  'weekly-bronze': {
    id: 'weekly-bronze',
    name: 'Weekly Bronze',
    nameKey: 'dailyChallenge.badges.weeklyBronze.name',
    icon: '🎗️',
    description: 'Complete 1 weekly challenge in one week',
    descriptionKey: 'dailyChallenge.badges.weeklyBronze.description',
  },
  'weekly-silver': {
    id: 'weekly-silver',
    name: 'Weekly Silver',
    nameKey: 'dailyChallenge.badges.weeklySilver.name',
    icon: '🏅',
    description: 'Complete 3 weekly challenges in one week',
    descriptionKey: 'dailyChallenge.badges.weeklySilver.description',
  },
  'weekly-gold': {
    id: 'weekly-gold',
    name: 'Weekly Gold',
    nameKey: 'dailyChallenge.badges.weeklyGold.name',
    icon: '🏆',
    description: 'Complete all 5 weekly challenges in one week',
    descriptionKey: 'dailyChallenge.badges.weeklyGold.description',
  },
};
