import type { PartyGameConfig, SongSelectionOption } from './unified-party-setup.types';

// ===================== DEFAULT GAME CONFIGURATIONS =====================

export const PARTY_GAME_CONFIGS: Record<string, PartyGameConfig> = {
  'pass-the-mic': {
    mode: 'pass-the-mic',
    title: 'Pass the Mic',
    icon: '🎤',
    description: 'Take turns singing parts of a song!',
    extendedDescription: [
      '🎵 Der Song wird in Segmente unterteilt',
      '🔄 Nach jedem Segment wechselt der Sänger',
      '🏆 Der Team-Score wird am Ende zusammengezählt',
    ],
    color: 'from-cyan-500 to-blue-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: false,
    forceInputMode: 'microphone',
    sharedMic: true,
  },
  'companion-singalong': {
    mode: 'companion-singalong',
    title: 'Companion Sing-A-Long',
    icon: '📱',
    description: 'Your phone randomly lights up - sing when it blinks!',
    extendedDescription: [
      '📱 Alle Spieler halten ihr Handy bereit',
      '⚡ Wenn das Handy aufleuchtet, bist du dran!',
      '🎤 Niemand weiß, wer als nächstes dran ist',
      '🏆 Sammle Punkte für dein Team',
    ],
    color: 'from-emerald-500 to-teal-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [
      { key: 'minTurnDuration', label: 'Min Turn Duration', type: 'slider', min: 5, max: 30, step: 5, defaultValue: 15, unit: 's' },
      { key: 'maxTurnDuration', label: 'Max Turn Duration', type: 'slider', min: 30, max: 90, step: 5, defaultValue: 45, unit: 's' },
      { key: 'blinkWarning', label: 'Blink Warning', description: 'Warning time before switch', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: true,
    forceInputMode: 'companion',
  },
  'companion-pass-the-mic': {
    mode: 'companion-pass-the-mic',
    title: 'Companion Pass the Mic',
    icon: '📱🎤',
    description: 'Sing segments via your phone — blink warns you before your turn!',
    extendedDescription: [
      '📱 Jeder Spieler singt über sein eigenes Handy',
      '🎵 Der Song wird in fair verteilte Segmente unterteilt',
      '⚡ Dein Handy blinkt 3 Sekunden bevor du dran bist',
      '🎤 "YOUR TURN!" erscheint auf dem Display',
      '🏆 Punkte basierend auf Tonhöhen-Genauigkeit',
      '🔄 Mehrere Runden mit Gesamtrangliste',
    ],
    color: 'from-violet-500 to-fuchsia-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [
      { key: 'blinkWarning', label: 'Blink-Warnung', description: 'Sekunden vor Segmentwechsel', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: true,
    forceInputMode: 'companion',
  },
  'medley': {
    mode: 'medley',
    title: 'Medley Contest',
    icon: '🎵',
    description: 'FFA or Team mode — sing random song snippets!',
    extendedDescription: [
      '👥 FFA: 4 Spieler singen gleichzeitig, einzeln bewertet',
      '⚔️ Team: 1v1 oder 2v2 — Teams treten in Duellen gegeneinander an',
      '🎵 Zufällige Song-Snippets — keine Vorschau, alles Überraschung!',
      '🏆 Punkte über alle Snippets summiert, zweite Runde möglich',
    ],
    color: 'from-purple-500 to-pink-500',
    minPlayers: 2,
    maxPlayers: 4,
    settings: [
      { key: 'playMode', label: 'Spielmodus', description: 'FFA, Team oder Elimination', type: 'select', options: [
        { value: 'ffa', label: 'FFA (Jeder gegen Jeden — 4 Spieler)' },
        { value: 'team', label: 'Team (1v1 oder 2v2)' },
        { value: 'elimination', label: '💀 Elimination (2-4 Spieler)' },
      ], defaultValue: 'ffa' },
      { key: 'teamSize', label: 'Team-Größe', description: 'Für Team-Modus', type: 'select', options: [
        { value: 1, label: '1v1 (5 Snippets)' },
        { value: 2, label: '2v2 (4 Snippets)' },
      ], defaultValue: 1 },
      { key: 'snippetDuration', label: 'Snippet-Dauer', type: 'slider', min: 15, max: 60, step: 5, defaultValue: 30, unit: 's' },
      { key: 'transitionTime', label: 'Übergangszeit', description: 'Zeit zwischen Snippets', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: true,
  },
  'tournament': {
    mode: 'tournament',
    title: 'Tournament Mode',
    icon: '🏆',
    description: 'Single elimination bracket - Sudden Death!',
    extendedDescription: [
      '🏆 K.O.-System: Verlierer scheidet aus',
      '⚔️ 1-gegen-1 Matches',
      '🎯 Short Mode: Nur 60 Sekunden pro Match',
      '👑 Der letzte Gewinner ist der Champion!',
    ],
    color: 'from-amber-500 to-yellow-500',
    minPlayers: 2,
    maxPlayers: 32,
    settings: [
      { key: 'maxPlayers', label: 'Bracket Size', type: 'select', options: [
        { value: 2, label: '2 - Duel' }, { value: 4, label: '4 Players' },
        { value: 8, label: '8 Players' }, { value: 16, label: '16 Players' }, { value: 32, label: '32 Players' },
      ], defaultValue: 8 },
      { key: 'shortMode', label: 'Short Mode', description: 'Each match lasts only 60 seconds', type: 'toggle', defaultValue: true },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'battle-royale': {
    mode: 'battle-royale',
    title: 'Battle Royale',
    icon: '👑',
    description: 'All sing together - lowest score eliminated each round! Up to 24 players (4 mic + 20 companion)',
    extendedDescription: [
      '🎤 Bis zu 4 Spieler mit Mikrofon am Gerät',
      '📱 Bis zu 20 weitere Spieler über die Companion App',
      '📉 Der Spieler mit der niedrigsten Punktzahl scheidet aus',
      '🔄 Jede Runde ein neuer Song (oder per Abstimmung)',
      '🎯 Kopfgeld-System: Jagd den Führenden!',
      '🏆 Grand Finale: Best-of-3 oder Best-of-5 für die letzten 2',
      '👑 Der letzte Sänger gewinnt!',
    ],
    color: 'from-red-600 to-pink-600',
    minPlayers: 2,
    maxPlayers: 24,
    settings: [
      { key: 'roundDuration', label: 'Round Duration', type: 'slider', min: 30, max: 180, step: 15, defaultValue: 60, unit: 's' },
      { key: 'finalRoundDuration', label: 'Final Round Duration', type: 'slider', min: 60, max: 300, step: 30, defaultValue: 120, unit: 's' },
      { key: 'medleyMode', label: 'Medley Mode', description: 'Multiple song snippets per round', type: 'toggle', defaultValue: false },
      { key: 'songSelection', label: 'Song Selection', description: 'How songs are chosen', type: 'select', options: [
        { value: 'random', label: '🎲 Random' },
        { value: 'vote', label: '🗳️ Vote (3 Songs)' },
      ], defaultValue: 'random' },
      { key: 'grandFinaleBestOf', label: 'Grand Finale', description: 'Final 2 players format', type: 'select', options: [
        { value: 1, label: 'Normal Final' },
        { value: 3, label: '🏆 Best of 3' },
        { value: 5, label: '🏆 Best of 5' },
      ], defaultValue: 1 },
      { key: 'bountyEnabled', label: 'Bounty System', description: 'Score multiplier for hunting the leader', type: 'toggle', defaultValue: true },
      { key: 'bountyMultiplier', label: 'Bounty Multiplier', type: 'slider', min: 1.2, max: 3, step: 0.1, defaultValue: 1.5, unit: 'x' },
      { key: 'escalatingDifficulty', label: 'Escalating Difficulty', description: 'Difficulty increases every 3 rounds', type: 'toggle', defaultValue: false },
      { key: 'shrinkingTimer', label: 'Shrinking Timer', description: 'Rounds get shorter over time', type: 'toggle', defaultValue: false },
      { key: 'noRepeatProtection', label: 'No-Repeat Protection', description: 'Prevent recently played songs', type: 'toggle', defaultValue: true },
    ],
    songSelectionOptions: ['random', 'vote'],
    supportsCompanionApp: true,
  },
  'duel': {
    mode: 'duel',
    title: 'Duel Mode',
    icon: '⚔️',
    description: 'Two players compete head-to-head!',
    extendedDescription: [
      '⚔️ 1-gegen-1 Duell',
      '🎤 Beide singen den gleichen Song',
      '📊 Punkte werden live verglichen',
      '🏆 Der Spieler mit der höheren Punktzahl gewinnt',
    ],
    color: 'from-cyan-500 to-pink-500',
    minPlayers: 2,
    maxPlayers: 2,
    settings: [],
    songSelectionOptions: ['library', 'random', 'vote'],
    supportsCompanionApp: false,
  },
  'blind': {
    mode: 'blind',
    title: 'Blind Karaoke',
    icon: '🙈',
    description: 'Musical passages go blind! Solo, Co-op, or Competitive.',
    extendedDescription: [
      '🙈 Ganze musikalische Passagen verschwinden (Strophe/Refrain/Bridge)',
      '🧠 Singe aus dem Gedächtnis ohne Noten-Hilfe',
      '🆘 Erste Strophe immer sichtbar als Orientierungshilfe',
      '🔥 HARDCORE: Wenn Noten sichtbar → Text versteckt (und umgekehrt)',
      '📈 Steigende Schwierigkeit: Häufigkeit wächst pro Runde',
      '👥 Solo, Kooperativ oder Kompetitiv (2–4 Spieler)',
      '🏆 Swiss-System Pairing für faire Runden',
    ],
    color: 'from-green-500 to-teal-500',
    minPlayers: 1,
    maxPlayers: 4,
    settings: [
      { key: 'blindFrequency', label: 'Blind Frequency', description: 'How often passages go blind', type: 'select', options: [
        { value: 'light', label: 'Light (15%)' }, { value: 'normal', label: 'Normal (30%)' },
        { value: 'hard', label: 'Hard (60%)' }, { value: 'insane', label: 'Insane (90%)' },
      ], defaultValue: 'normal' },
      { key: 'hardcore', label: 'Hardcore Mode', description: 'Text hidden when notes visible, and vice versa', type: 'toggle', defaultValue: false },
      { key: 'escalating', label: 'Escalating', description: 'Frequency increases each round', type: 'toggle', defaultValue: false },
      { key: 'bestOf', label: 'Best of', description: 'Number of rounds per player', type: 'select', options: [
        { value: 1, label: '1 Round' }, { value: 3, label: 'Best of 3' },
        { value: 5, label: 'Best of 5' }, { value: 7, label: 'Best of 7' },
      ], defaultValue: 3 },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'missing-words': {
    mode: 'missing-words',
    title: 'Missing Words',
    icon: '📝',
    description: 'Words or passages disappear! Solo, Co-op, or Competitive.',
    extendedDescription: [
      '📝 Wörter oder ganze Textpassagen verschwinden',
      '🎤 Die erste Strophe bleibt immer sichtbar als Anhaltspunkt',
      '🎯 3 Versteck-Modi: Wörter, Passagen oder Beides',
      '🔥 Hardcore: Versteckte Wörter bleiben bis zum Ende verborgen',
      '📈 Steigende Schwierigkeit: Häufigkeit wächst pro Runde',
      '⭐ Erweiterte Bonusse: Streak, Perfect, Comeback',
      '👥 Solo, Kooperativ oder Kompetitiv (2–4 Spieler)',
      '🏆 Swiss-System Pairing für faire Runden',
    ],
    color: 'from-orange-500 to-red-500',
    minPlayers: 1,
    maxPlayers: 4,
    settings: [
      { key: 'missingWordFrequency', label: 'Missing Words Frequency', description: 'How much text is hidden', type: 'select', options: [
        { value: 'light', label: 'Light (15%)' }, { value: 'normal', label: 'Normal (30%)' },
        { value: 'hard', label: 'Hard (60%)' }, { value: 'insane', label: 'Insane (90%)' },
      ], defaultValue: 'normal' },
      { key: 'granularity', label: 'Hiding Mode', description: 'Words, passages, or both', type: 'select', options: [
        { value: 'word', label: 'Words' }, { value: 'passage', label: 'Passages' }, { value: 'both', label: 'Both' },
      ], defaultValue: 'passage' },
      { key: 'hardcoreMissingWords', label: 'Hardcore Mode', description: 'Hidden words stay hidden until song ends', type: 'toggle', defaultValue: false },
      { key: 'escalating', label: 'Escalating', description: 'Frequency increases each round', type: 'toggle', defaultValue: false },
      { key: 'bestOf', label: 'Best of', description: 'Number of rounds per player', type: 'select', options: [
        { value: 1, label: '1 Round' }, { value: 3, label: 'Best of 3' },
        { value: 5, label: 'Best of 5' }, { value: 7, label: 'Best of 7' },
      ], defaultValue: 3 },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'rate-my-song': {
    mode: 'rate-my-song',
    title: 'Rate my Song',
    icon: '⭐',
    description: 'Sing a song and let friends rate your performance!',
    extendedDescription: [
      '🎤 Singe einen Song deiner Wahl',
      '⭐ 4 Bewertungskategorien mit gewichtetem Gesamtergebnis',
      '🎯 Challenges & Tipps für extra Spaß',
      '🏆 Ränge, Achievements & Hall of Fame',
      '📊 Multi-Round-Serien mit Gesamtwertung',
    ],
    color: 'from-amber-500 to-orange-500',
    minPlayers: 1,
    maxPlayers: 2,
    settings: [
      { key: 'duration', label: 'Dauer', type: 'select', options: [
        { value: 'short', label: 'Kurz (60s)' },
        { value: 'normal', label: 'Normal' },
      ], defaultValue: 'normal' },
      { key: 'seriesRounds', label: 'Runden', type: 'select', options: [
        { value: 1, label: '1 Runde' },
        { value: 3, label: '3 Runden' },
        { value: 5, label: '5 Runden' },
        { value: 7, label: '7 Runden' },
      ], defaultValue: 1 },
      { key: 'categoriesEnabled', label: 'Kategorien', description: '4 Bewertungskategorien statt Einzelscore', type: 'toggle', defaultValue: true },
      { key: 'challengesEnabled', label: 'Challenges', description: 'Zufällige Challenges vor jeder Runde', type: 'toggle', defaultValue: false },
      { key: 'bettingEnabled', label: 'Tippen', description: 'Publikum kann vorhersagen', type: 'toggle', defaultValue: false },
    ],
    songSelectionOptions: ['library', 'random'],
    supportsCompanionApp: true,
  },
};

// ===================== SONG SELECTION BUTTONS CONFIG =====================

export const SONG_SELECTION_CONFIG: Record<SongSelectionOption, {
  icon: string; label: string; description: string; color: string;
}> = {
  library: { icon: '📚', label: 'From Library', description: 'Choose a song from your library', color: 'bg-cyan-500 hover:bg-cyan-600' },
  random: { icon: '🎲', label: 'Random Song', description: 'Let the game pick a random song', color: 'bg-purple-500 hover:bg-purple-600' },
  vote: { icon: '🗳️', label: 'Vote (3 Songs)', description: '3 songs are suggested - vote for your favorite', color: 'bg-amber-500 hover:bg-amber-600' },
  medley: { icon: '🎵', label: 'Medley Mix', description: 'Mix multiple songs together', color: 'bg-pink-500 hover:bg-pink-600' },
};
