import type { PartyGameConfig, SongSelectionOption } from './unified-party-setup.types';

// ===================== DEFAULT GAME CONFIGURATIONS =====================

export const PARTY_GAME_CONFIGS: Record<string, PartyGameConfig> = {
  'pass-the-mic': {
    mode: 'pass-the-mic',
    title: 'Pass the Mic',
    icon: '🎤',
    description: 'Take turns singing parts of a song!',
    extendedDescriptionKey: 'passTheMic',
    color: 'from-cyan-500 to-blue-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: false,
    forceInputMode: 'microphone',
    sharedMic: true,
  },
  'companion-singalong': {
    mode: 'companion-singalong',
    title: 'Companion Sing-A-Long',
    icon: '📱',
    description: 'Your phone randomly lights up - sing when it blinks!',
    extendedDescriptionKey: 'companionSingalong',
    color: 'from-emerald-500 to-teal-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [
      { key: 'minTurnDuration', label: 'Min Turn Duration', type: 'slider', min: 5, max: 30, step: 5, defaultValue: 15, unit: 's' },
      { key: 'maxTurnDuration', label: 'Max Turn Duration', type: 'slider', min: 30, max: 90, step: 5, defaultValue: 45, unit: 's' },
      { key: 'blinkWarning', label: 'Blink Warning', description: 'Warning time before switch', labelKey: 'modeSettings.blinkWarning', descriptionKey: 'modeSettings.blinkWarningDesc', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: true,
    forceInputMode: 'companion',
  },
  'companion-pass-the-mic': {
    mode: 'companion-pass-the-mic',
    title: 'Companion Pass the Mic',
    icon: '📱🎤',
    description: 'Sing segments via your phone — blink warns you before your turn!',
    extendedDescriptionKey: 'companionPassTheMic',
    color: 'from-violet-500 to-fuchsia-500',
    minPlayers: 2,
    maxPlayers: 8,
    settings: [
      { key: 'blinkWarning', label: 'Blink Warning', description: 'Seconds before segment change', labelKey: 'modeSettings.blinkWarning', descriptionKey: 'modeSettings.blinkWarningDesc', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['library', 'random', 'vote', 'medley'],
    supportsCompanionApp: true,
    forceInputMode: 'companion',
  },
  'medley': {
    mode: 'medley',
    title: 'Medley Contest',
    icon: '🎵',
    description: 'FFA or Team mode — sing random song snippets!',
    extendedDescriptionKey: 'medley',
    color: 'from-purple-500 to-pink-500',
    minPlayers: 2,
    maxPlayers: 4,
    settings: [
      { key: 'playMode', label: 'Play Mode', description: 'FFA, Team or Elimination', labelKey: 'modeSettings.playMode', descriptionKey: 'modeSettings.playModeDesc', type: 'select', options: [
        { value: 'ffa', label: 'FFA (Everyone vs Everyone — 4 Players)', labelKey: 'modeSettings.ffa' },
        { value: 'team', label: 'Team (1v1 or 2v2)', labelKey: 'modeSettings.team' },
        { value: 'elimination', label: '💀 Elimination (2-4 Players)', labelKey: 'modeSettings.elimination' },
      ], defaultValue: 'ffa' },
      { key: 'teamSize', label: 'Team Size', description: 'For team mode', labelKey: 'modeSettings.teamSize', descriptionKey: 'modeSettings.teamSizeDesc', type: 'select', options: [
        { value: 1, label: '1v1 (5 Snippets)' },
        { value: 2, label: '2v2 (4 Snippets)' },
      ], defaultValue: 1 },
      { key: 'snippetDuration', label: 'Snippet Duration', labelKey: 'modeSettings.snippetDuration', type: 'slider', min: 15, max: 60, step: 5, defaultValue: 30, unit: 's' },
      { key: 'transitionTime', label: 'Transition Time', description: 'Time between snippets', labelKey: 'modeSettings.transitionTime', descriptionKey: 'modeSettings.transitionTimeDesc', type: 'slider', min: 1, max: 5, step: 1, defaultValue: 3, unit: 's' },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: true,
  },
  'tournament': {
    mode: 'tournament',
    title: 'Tournament Mode',
    icon: '🏆',
    description: 'Single elimination bracket - Sudden Death!',
    extendedDescriptionKey: 'tournament',
    color: 'from-amber-500 to-yellow-500',
    minPlayers: 2,
    maxPlayers: 32,
    settings: [
      { key: 'maxPlayers', label: 'Bracket Size', type: 'select', options: [
        { value: 2, label: '2 - Duel' }, { value: 4, label: '4 Players' },
        { value: 8, label: '8 Players' }, { value: 16, label: '16 Players' }, { value: 32, label: '32 Players' },
      ], defaultValue: 8 },
      { key: 'shortMode', label: 'Short Mode', description: 'Each match lasts only 60 seconds', type: 'toggle', defaultValue: true },
      { key: 'tournamentType', label: 'Tournament Type', labelKey: 'tournament.type', type: 'select', options: [
        { value: 'single', label: 'Single Elimination' },
        { value: 'double', label: 'Double Elimination' },
      ], defaultValue: 'single' },
      { key: 'tiebreakMode', label: 'Tiebreak Mode', labelKey: 'tournament.tiebreak', type: 'select', options: [
        { value: 'coinflip', label: 'Coin Flip' },
        { value: 'accuracy', label: 'Accuracy' },
        { value: 'combo', label: 'Max Combo' },
        { value: 'goldenmic', label: 'Golden Mic' },
      ], defaultValue: 'accuracy' },
      { key: 'dynamicDifficulty', label: 'Dynamic Difficulty', labelKey: 'tournament.dynamicDifficulty', type: 'toggle', defaultValue: false },
      { key: 'songSelectionMode', label: 'Song Selection Mode', labelKey: 'tournament.songSelection', type: 'select', options: [
        { value: 'random', label: 'Random' },
        { value: 'vote', label: 'Vote' },
      ], defaultValue: 'random' },
      { key: 'seedingMode', label: 'Seeding Mode', labelKey: 'tournament.seeding', type: 'select', options: [
        { value: 'random', label: 'Random' },
        { value: 'strength', label: 'By Strength' },
      ], defaultValue: 'random' },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'battle-royale': {
    mode: 'battle-royale',
    title: 'Battle Royale',
    icon: '👑',
    description: 'All sing together - lowest score eliminated each round! Up to 24 players (4 mic + 20 companion)',
    extendedDescriptionKey: 'battleRoyale',
    color: 'from-red-600 to-pink-600',
    minPlayers: 2,
    maxPlayers: 24,
    settings: [
      { key: 'roundDuration', label: 'Round Duration', type: 'slider', min: 30, max: 180, step: 15, defaultValue: 60, unit: 's' },
      { key: 'finalRoundDuration', label: 'Final Round Duration', type: 'slider', min: 60, max: 300, step: 30, defaultValue: 120, unit: 's' },
      { key: 'medleyMode', label: 'Medley Mode', description: 'Multiple song snippets per round', type: 'toggle', defaultValue: false },
      // NOTE: Song selection method is controlled by the top-level songSelectionOptions (random|vote),
      // NOT by an inner setting. The UI renders selection buttons based on songSelectionOptions.
      { key: 'grandFinaleBestOf', label: 'Grand Finale', description: 'Final 2 players format', type: 'select', options: [
        { value: 1, label: 'Normal Final' },
        { value: 3, label: '🏆 Best of 3' },
        { value: 5, label: '🏆 Best of 5' },
      ], defaultValue: 1 },
      { key: 'bountyEnabled', label: 'Bounty System', description: 'Score multiplier for hunting the leader', type: 'toggle', defaultValue: true },
      { key: 'bountyMultiplier', label: 'Bounty Multiplier', type: 'slider', min: 1.2, max: 3, step: 0.1, defaultValue: 1.5, unit: 'x' },
      { key: 'escalatingDifficulty', label: 'Escalating Difficulty', description: 'Difficulty increases every 3 rounds', type: 'toggle', defaultValue: false },
      { key: 'shrinkingTimer', label: 'Shrinking Timer', description: 'Rounds get shorter over time', type: 'toggle', defaultValue: false },
      { key: 'noRepeatProtection', label: 'No-Repeat Protection', description: 'Prevent recently played songs', type: 'toggle', defaultValue: true },
    ],
    songSelectionOptions: ['random', 'vote'],
    supportsCompanionApp: true,
  },
  'duel': {
    mode: 'duel',
    title: 'Duel Mode',
    icon: '⚔️',
    description: 'Two players compete head-to-head!',
    extendedDescriptionKey: 'duel',
    color: 'from-cyan-500 to-pink-500',
    minPlayers: 2,
    maxPlayers: 2,
    settings: [],
    songSelectionOptions: ['library', 'random', 'vote'],
    supportsCompanionApp: false,
  },
  'blind': {
    mode: 'blind',
    title: 'Blind Karaoke',
    icon: '🙈',
    description: 'Musical passages go blind! Solo, Co-op, or Competitive.',
    extendedDescriptionKey: 'blind',
    color: 'from-green-500 to-teal-500',
    minPlayers: 1,
    maxPlayers: 4,
    settings: [
      { key: 'blindFrequency', label: 'Blind Frequency', description: 'How often passages go blind', type: 'select', options: [
        { value: 'light', label: 'Light (15%)' }, { value: 'normal', label: 'Normal (30%)' },
        { value: 'hard', label: 'Hard (60%)' }, { value: 'insane', label: 'Insane (90%)' },
      ], defaultValue: 'normal' },
      { key: 'hardcore', label: 'Hardcore Mode', description: 'Text hidden when notes visible, and vice versa', type: 'toggle', defaultValue: false },
      { key: 'escalating', label: 'Escalating', description: 'Frequency increases each round', type: 'toggle', defaultValue: false },
      { key: 'bestOf', label: 'Best of', description: 'Number of rounds per player', type: 'select', options: [
        { value: 1, label: '1 Round' }, { value: 3, label: 'Best of 3' },
        { value: 5, label: 'Best of 5' }, { value: 7, label: 'Best of 7' },
      ], defaultValue: 3 },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'missing-words': {
    mode: 'missing-words',
    title: 'Missing Words',
    icon: '📝',
    description: 'Words or passages disappear! Solo, Co-op, or Competitive.',
    extendedDescriptionKey: 'missingWords',
    color: 'from-orange-500 to-red-500',
    minPlayers: 1,
    maxPlayers: 4,
    settings: [
      { key: 'missingWordFrequency', label: 'Missing Words Frequency', description: 'How much text is hidden', type: 'select', options: [
        { value: 'light', label: 'Light (15%)' }, { value: 'normal', label: 'Normal (30%)' },
        { value: 'hard', label: 'Hard (60%)' }, { value: 'insane', label: 'Insane (90%)' },
      ], defaultValue: 'normal' },
      { key: 'granularity', label: 'Hiding Mode', description: 'Words, passages, or both', type: 'select', options: [
        { value: 'word', label: 'Words' }, { value: 'passage', label: 'Passages' }, { value: 'both', label: 'Both' },
      ], defaultValue: 'passage' },
      { key: 'hardcoreMissingWords', label: 'Hardcore Mode', description: 'Hidden words stay hidden until song ends', type: 'toggle', defaultValue: false },
      { key: 'escalating', label: 'Escalating', description: 'Frequency increases each round', type: 'toggle', defaultValue: false },
      { key: 'bestOf', label: 'Best of', description: 'Number of rounds per player', type: 'select', options: [
        { value: 1, label: '1 Round' }, { value: 3, label: 'Best of 3' },
        { value: 5, label: 'Best of 5' }, { value: 7, label: 'Best of 7' },
      ], defaultValue: 3 },
    ],
    songSelectionOptions: ['random'],
    supportsCompanionApp: false,
  },
  'rate-my-song': {
    mode: 'rate-my-song',
    title: 'Rate my Song',
    icon: '⭐',
    description: 'Sing a song and let friends rate your performance!',
    extendedDescriptionKey: 'rateMySong',
    color: 'from-amber-500 to-orange-500',
    minPlayers: 1,
    maxPlayers: 2,
    settings: [
      { key: 'duration', label: 'Duration', labelKey: 'modeSettings.duration', type: 'select', options: [
        { value: 'short', label: 'Short (60s)', labelKey: 'modeSettings.short60s' },
        { value: 'normal', label: 'Normal', labelKey: 'modeSettings.normalDuration' },
      ], defaultValue: 'normal' },
      { key: 'seriesRounds', label: 'Rounds', labelKey: 'modeSettings.seriesRounds', type: 'select', options: [
        { value: 1, label: '1 Round', labelKey: 'modeSettings.round1' },
        { value: 3, label: '3 Rounds', labelKey: 'modeSettings.rounds3' },
        { value: 5, label: '5 Rounds', labelKey: 'modeSettings.rounds5' },
        { value: 7, label: '7 Rounds', labelKey: 'modeSettings.rounds7' },
      ], defaultValue: 1 },
      { key: 'categoriesEnabled', label: 'Categories', description: '4 rating categories instead of single score', labelKey: 'modeSettings.categories', descriptionKey: 'modeSettings.categoriesDesc', type: 'toggle', defaultValue: true },
      { key: 'challengesEnabled', label: 'Challenges', description: 'Random challenges before each round', labelKey: 'modeSettings.challenges', descriptionKey: 'modeSettings.challengesDesc', type: 'toggle', defaultValue: false },
      { key: 'bettingEnabled', label: 'Betting', description: 'Audience can predict', labelKey: 'modeSettings.betting', descriptionKey: 'modeSettings.bettingDesc', type: 'toggle', defaultValue: false },
    ],
    songSelectionOptions: ['library', 'random'],
    supportsCompanionApp: true,
  },
};

// ===================== SONG SELECTION BUTTONS CONFIG =====================

export const SONG_SELECTION_CONFIG: Record<SongSelectionOption, {
  icon: string; label: string; labelKey: string; description: string; descriptionKey: string; color: string;
}> = {
  library: { icon: '📚', label: 'From Library', labelKey: 'unifiedSetup.fromLibrary', description: 'Choose a song from your library', descriptionKey: 'unifiedSetup.fromLibraryDesc', color: 'bg-cyan-500 hover:bg-cyan-600' },
  random: { icon: '🎲', label: 'Random Song', labelKey: 'unifiedSetup.randomSong', description: 'Let the game pick a random song', descriptionKey: 'unifiedSetup.randomSongDesc', color: 'bg-purple-500 hover:bg-purple-600' },
  vote: { icon: '🗳️', label: 'Vote (3 Songs)', labelKey: 'unifiedSetup.voteSongs', description: '3 songs are suggested - vote for your favorite', descriptionKey: 'unifiedSetup.voteSongsDesc', color: 'bg-amber-500 hover:bg-amber-600' },
  medley: { icon: '🎵', label: 'Medley Mix', labelKey: 'unifiedSetup.medleyMix', description: 'Mix multiple songs together', descriptionKey: 'unifiedSetup.medleyMixDesc', color: 'bg-pink-500 hover:bg-pink-600' },
};
