#!/usr/bin/env python3
"""R33-f1: i18n-Propagation der 143 R33-Companion-Keys in 7 Sprachen (es, fr, it, pt, ja, ko, zh).

Quellen: src/lib/i18n/pending-keys/r33-{c,d1,d2,d3,d4,e}.json (EN/DE Werte).
Ziele je Sprache:
  mobile.ts   - flache mobile.*-Keys + hotkeys-Block nach `mobile: {`
              - NEUES Top-Level-Objekt mobileHelp nach `export const mobileTranslations = {`
              - mobileViews.* nach `mobileViews: {`
  settings.ts - settings.loudnessNormalization nach `settings: {`
  tutorial.ts - tutorial.companion.chapters.{control,solo,help} nach chapters.features
              - 10 neue Steps zwischen singAlong und deviceList (wie en/de)

Muster: scripts/merge-pending-keys.py (v2, tail-safe — Datei-Rest wird immer wieder angehängt).
Idempotent: Block-Keys bereits vorhanden -> Skip. KEIN build/tsc/lint, keine Commits.
"""
import json, glob, re, sys

LANGS = ['es', 'fr', 'it', 'pt', 'ja', 'ko', 'zh']
BASE = 'src/lib/i18n/locales'

# ── Keys aus den pending-keys-JSONs laden (Reihenfolge = Einfüge-Reihenfolge) ──
entries = []          # list of dicts in file/key order
by_key = {}
for f in sorted(glob.glob('src/lib/i18n/pending-keys/r33-*.json')):
    for e in json.load(open(f, encoding='utf-8')):
        if e['key'] not in by_key:
            entries.append(e)
            by_key[e['key']] = e
ALL_KEYS = [e['key'] for e in entries]

def leaf(k): return k.split('.')[-1]

FLAT     = [k for k in ALL_KEYS if k.startswith('mobile.') and not k.startswith('mobile.hotkeys.')]
HOTKEYS  = [k for k in ALL_KEYS if k.startswith('mobile.hotkeys.')]
HELP     = [k for k in ALL_KEYS if k.startswith('mobileHelp.')]
VIEWS    = [k for k in ALL_KEYS if k.startswith('mobileViews.')]
SETTINGS = [k for k in ALL_KEYS if k.startswith('settings.')]
TUT_CH   = [k for k in ALL_KEYS if k.startswith('tutorial.companion.chapters.')]
TUT_STEP = [k for k in ALL_KEYS if k.startswith('tutorial.companion.steps.')]

STEPS_ORDER = []      # ['takeControl', 'controlSync', ...]
for k in TUT_STEP:
    s = k.split('.')[3]
    if s not in STEPS_ORDER:
        STEPS_ORDER.append(s)

# ════════════════════════════ ÜBERSETZUNGEN ════════════════════════════
T = {}

# ─────────────────────────────── ESPAÑOL (tú) ───────────────────────────────
T['es'] = {
  'mobile.toastControlAcquired': 'Control tomado',
  'mobile.toastControlReleased': 'Control liberado',
  'mobile.toastControlLost': 'Control perdido',
  'mobile.toastControlTaken': 'El control ya está ocupado',
  'mobile.toastLockedNav': 'Solo con control remoto',
  'mobile.homeControlYouTitle': 'Tú controlas el escritorio',
  'mobile.homeControlYouDesc': 'Tus pestañas dirigen el escritorio — todas las áreas están desbloqueadas.',
  'mobile.homeCurrentSong': 'Canción actual',
  'mobile.homeHotkeysTitle': 'Atajos del escritorio',
  'mobile.homeHotkeysDesc': 'Los atajos de teclado más importantes del escritorio',
  'mobile.homeRequestSong': 'Pedir una canción',
  'mobile.homeTakeControlForFull': 'Toma el control para acceso total',
  'mobile.homeControlByTitle': 'El control lo tiene {name}',
  'mobile.homeControlFreeTitle': 'Sin control activo',
  'mobile.homeControlHintDesc': 'Sin control puedes pedir canciones, chatear y participar.',
  'mobile.mirrorSettingsSubtitle': 'Controla los ajustes del escritorio en directo desde tu teléfono',
  'mobile.mirrorSettingsNoSnapshot': 'Valores del escritorio aún no recibidos — se muestran los valores predeterminados',
  'mobile.mirrorSettingsNeedControl': 'Toma el control remoto para enviar cambios al escritorio',
  'mobile.mirrorSettingsWebcamNone': 'Todavía no hay ninguna webcam configurada en el escritorio. Actívala aquí para crear una configuración predeterminada.',
  'mobile.mirrorSettingsWebcamSent': 'Los cambios se guardan en el escritorio y surten efecto con la próxima canción.',
  'mobile.mirrorLoadError': 'No se pudieron cargar los datos.',
  'mobile.mirrorRetry': 'Reintentar',
  'mobile.mirrorNoProfileLink': 'No hay perfil vinculado. Conecta la app compañera a un perfil para ver tus datos.',
  'mobile.mirrorProfileMissing': 'Tu perfil no se ha encontrado en el escritorio. Tus logros aparecerán aquí en cuanto se sincronice el perfil del escritorio.',
  'mobile.mirrorOnlyMine': 'Solo míos',
  'mobile.mirrorAll': 'Todos',
  'mobile.mirrorEntries': '{n} entradas',
  'mobile.mirrorDailyNoData': 'No hay datos diarios para tu perfil.',
  'mobile.mirrorDailyControlHint': 'Solo visualización — toma el control para iniciar retos.',
  'mobile.mirrorDailyModesHint': 'Los modos de reto se juegan en el escritorio — este es el catálogo.',
  'mobile.mirrorSlotsToday': '{n}/{m} plazas hoy',
  'mobile.mirrorPlayer': 'Jugador',
  'mobile.mirrorProfileYou': 'Tú',
  'mobile.mirrorProfileControlHint': 'Solo visualización — toma el control para activar o desactivar perfiles.',
  'mobile.mirrorSongsShort': 'Canciones',
  'mobile.mirrorJukeboxFilters': 'Filtros',
  'mobile.mirrorJukeboxFilterSet': 'Establecer filtros',
  'mobile.mirrorJukeboxFilterRemove': 'Quitar filtro',
  'mobile.mirrorJukeboxNoFilters': 'Ningún filtro activo — la Jukebox reproduce desde todo el repertorio.',
  'mobile.mirrorJukeboxFilterGenre': 'Género',
  'mobile.mirrorJukeboxFilterArtist': 'Artista',
  'mobile.mirrorJukeboxFilterEra': 'Década',
  'mobile.mirrorJukeboxFilterYear': 'Año',
  'mobile.mirrorJukeboxFilterAllArtists': 'Todos los artistas',
  'mobile.mirrorJukeboxFilterAllEras': 'Todas las décadas',
  'mobile.mirrorJukeboxFilterAllYears': 'Todos los años',
  'mobile.mirrorJukeboxFilterApplied': 'Filtro aplicado — surte efecto en el escritorio.',
  'mobile.mirrorJukeboxFilterCleared': 'Filtro quitado.',
  'mobile.mirrorJukeboxNoLibrary': 'Cargando biblioteca…',
  'mobile.mirrorJukeboxStateChipPool': 'Repertorio',
  'mobile.mirrorJukeboxPoolAll': 'Todas las canciones',
  'mobile.mirrorJukeboxPlaylistsTitle': 'Playlists y repertorio',
  'mobile.mirrorJukeboxPlaylistSongs': '{n} canciones',
  'mobile.mirrorJukeboxSystemBadge': 'Sistema',
  'mobile.mirrorJukeboxSetPool': 'Establecer como repertorio',
  'mobile.mirrorJukeboxActivePool': 'Repertorio activo',
  'mobile.mirrorJukeboxPoolSet': 'Repertorio de canciones establecido.',
  'mobile.mirrorJukeboxPoolCleared': 'Repertorio restablecido — todas las canciones.',
  'mobile.mirrorJukeboxEnqueue': 'A la lista de deseos',
  'mobile.mirrorJukeboxEnqueueConfirm': '¿Encolar?',
  'mobile.mirrorJukeboxEnqueued': 'Playlist encolada — sonará pronto en el escritorio.',
  'mobile.mirrorJukeboxPlaylistsEmpty': 'Aún no hay playlists.',
  'mobile.mirrorJukeboxPlaylistsError': 'No se pudieron cargar las playlists.',
  'mobile.mirrorJukeboxRefresh': 'Actualizar',
  'mobile.mirrorJukeboxRequestedBy': 'de',
  'mobile.mirrorQueueEmptyTitle': 'Aún no hay peticiones',
  'mobile.mirrorQueueEmptyBrowse': '¡Explora la biblioteca y elige una canción!',
  'mobile.mirrorQueueDesktopControls': 'El escritorio decide cuándo se canta',
  'mobile.queueSlotsFull': 'Todas las plazas ocupadas',
  'mobile.hotkeys.cardTitle': 'Atajos de teclado',
  'mobile.hotkeys.cardHint': 'Los atajos más importantes para el escritorio',
  'mobile.hotkeys.collapse': 'Plegar atajos de teclado',
  'mobile.hotkeys.expand': 'Desplegar atajos de teclado',
  'mobile.hotkeys.esc': 'Pausa / atrás / cancelar',
  'mobile.hotkeys.enter': 'Reanudar (en pausa)',
  'mobile.hotkeys.f12': 'Activar/desactivar pantalla completa',
  'mobile.hotkeys.ctrlL': 'Enfocar la búsqueda de la biblioteca',
  'mobile.hotkeys.ctrlR': 'Canción aleatoria (individual)',
  'mobile.hotkeys.ctrlD': 'Canción aleatoria (duelo)',
  'mobile.hotkeys.ctrlQ': 'Reproducir la siguiente canción de la cola',
  'mobile.hotkeys.ctrlJ': 'Abrir la Jukebox',
  'mobile.hotkeys.fkeys': 'Ir directo a pantallas: F1 Inicio · F2 Biblioteca · F3 Fiesta · F4 Cola · F5 Perfiles · F6 Puntuaciones · F7 Logros · F8 Jukebox · F9 Ajustes · F10 Editor',
  'mobileHelp.title': 'Ayuda',
  'mobileHelp.close': 'Cerrar',
  'mobileHelp.intro': 'App Companion: todo lo importante sobre conexión, control remoto, participación y canto — en cinco capítulos cortos.',
  'mobileHelp.ch1Title': 'Conexión y micrófono',
  'mobileHelp.ch1b1': 'Escanea el código QR del escritorio o abre el enlace Companion — el móvil y el PC deben estar en la misma red WiFi.',
  'mobileHelp.ch1b2': 'Crea un perfil (nombre, color, foto) — se sincroniza automáticamente con el escritorio.',
  'mobileHelp.ch1b3': 'La primera vez que cantas, el navegador pide acceso al micrófono — toca "Permitir".',
  'mobileHelp.ch1b4': 'El código arriba a la derecha del encabezado indica que la conexión está activa.',
  'mobileHelp.ch2Title': 'Control remoto: tomar el control',
  'mobileHelp.ch2b1': 'Con "Tomar control", tu teléfono refleja la pantalla del escritorio — siempre ves lo que corre en el PC.',
  'mobileHelp.ch2b2': 'Tu barra de pestañas maneja entonces el escritorio: inicio, biblioteca, fiesta, cola, Jukebox, puntuaciones, logros, ajustes.',
  'mobileHelp.ch2b3': 'Desde la página de inicio puedes pausar o saltar la canción en curso.',
  'mobileHelp.ch2b4': 'Solo UN dispositivo controla a la vez — "Liberar control" deja el puesto libre.',
  'mobileHelp.ch3Title': 'Sin control',
  'mobileHelp.ch3b1': 'Pedir canciones: abre la biblioteca, toca una canción, elige tus opciones (modo, dificultad, micro) y añádela a la cola — hasta 3 canciones.',
  'mobileHelp.ch3b2': 'Chat: toca 💬 arriba a la derecha y habla con el anfitrión y los demás jugadores.',
  'mobileHelp.ch3b3': 'Fiesta: votas en las votaciones de canciones, ves las señales de turno y cantas cuando te toca — todo mediante paneles emergentes, sin necesidad de control.',
  'mobileHelp.ch3b4': 'Tus propios logros y puntuaciones están en la barra de pestañas (🏅 logros, 🏆 puntuaciones).',
  'mobileHelp.ch3b5': 'Las áreas con candado (ajustes, perfiles, fiesta, reto, Jukebox) necesitan control remoto — tu propio perfil puedes editarlo siempre.',
  'mobileHelp.ch4Title': 'Cantar con el teléfono',
  'mobileHelp.ch4b1': 'Cuando te toca cantar en el juego, el micrófono se inicia automáticamente — en Battle Royale todos cantan a la vez.',
  'mobileHelp.ch4b2': 'La barra fina bajo el encabezado muestra el volumen y la nota detectada de tu canto.',
  'mobileHelp.ch4b3': 'Sostén el teléfono cerca de la boca y mantén la música de los altavoces lejos del dispositivo.',
  'mobileHelp.ch5Title': 'Solución de problemas',
  'mobileHelp.ch5b1': 'Conexión perdida: la app se reconecta automáticamente. Si no, revisa la WiFi y toca "Reintentar Conexión".',
  'mobileHelp.ch5b2': 'Sin micrófono/sonido: revisa el permiso del micrófono en los ajustes del sitio del navegador.',
  'mobileHelp.ch5b3': 'El espejo queda vacío: el escritorio (la app de PC) debe estar en marcha y en la misma red.',
  'mobileHelp.ch5b4': 'El control no responde: otro dispositivo tiene el control — la tarjeta de estado de la página de inicio muestra quién controla.',
  'mobileHelp.localOnlyNote': 'Esta ayuda corre completamente en tu teléfono — no controla el escritorio.',
  'mobileViews.desktopDefaultDifficulty': 'Predeterminado del escritorio',
  'mobileViews.queueAddAction': 'Añadir a la cola',
  'settings.loudnessNormalization': 'Normalización de volumen (objetivo de 89 dB)',
  'tutorial.companion.chapters.control': 'Control remoto: Take Control',
  'tutorial.companion.chapters.solo': 'Sin control',
  'tutorial.companion.chapters.help': 'Ayuda del Companion',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': 'Un teléfono ahora maneja el escritorio solo bajo orden: el botón "Tomar control" del Companion se lleva el mando remoto — antes y después, el teléfono toca solo para sí mismo.',
  'tutorial.companion.steps.takeControl.details': 'El mecanismo detrás de "Tomar control":\n• El control se reserva de forma exclusiva para un único dispositivo (bloqueo remoto).\n• El escritorio y el teléfono que controla van sincronizados: cada lado ve al instante lo que hace el otro.\n• Los demás teléfonos muestran el estado "Controlado por …" y esperan.\n\nEl control termina con "Liberar" — o automáticamente si el teléfono pierde la conexión.',
  'tutorial.companion.steps.controlSync.title': 'Escritorio y teléfono en sincronía',
  'tutorial.companion.steps.controlSync.body': 'De vuelta en la pestaña Móvil: aquí ves, como anfitrión, todos los dispositivos. Cuando un teléfono toma el control, refleja la pantalla del escritorio y maneja pantallas, botones y confirmaciones — el ratón y el teclado del escritorio siguen totalmente utilizables.',
  'tutorial.companion.steps.controlSync.details': 'Como ambos lados van sincronizados, nadie puede "tocar y salir corriendo": haces clic en el escritorio y el teléfono que controla sigue — tocas en el teléfono y el escritorio cambia de pantalla.\n\nEn la lista de dispositivos reconoces al que controla por su insignia de mando remoto.',
  'tutorial.companion.steps.controlHandover.title': 'Solo un mando remoto a la vez',
  'tutorial.companion.steps.controlHandover.body': 'El control es exclusivo: mientras un teléfono maneja, ningún otro puede tomarlo — su botón muestra en cambio quién controla. Liberar o desconectar devuelve el control al instante.',
  'tutorial.companion.steps.controlHandover.details': 'Conviene saber:\n• El anfitrión puede seguir haciendo clic en cualquier momento — el teléfono que controla lo sigue (y conserva el control).\n• Si el teléfono que controla pierde la conexión (batería, WiFi), el control vuelve automáticamente al escritorio.\n• Una expulsión de la lista de dispositivos también termina el control.',
  'tutorial.companion.steps.soloOverview.title': 'Invitados sin control 🙋',
  'tutorial.companion.steps.soloOverview.body': 'La mayoría de los invitados nunca necesitan el mando: los teléfonos conectados sin Take Control son acompañantes autónomos — piden canciones, chatean, cantan y consultan sus propios logros sin tocar el escritorio.',
  'tutorial.companion.steps.soloOverview.details': 'Lo que pueden hacer los teléfonos sin control:\n• 🎵 Encolar sus propias canciones (con la insignia 📱)\n• 💬 Unirse al chat de la fiesta\n• 🎤 Cantar en los modos de fiesta (Companion Sing-A-Long, Pasa el Micrófono)\n• 🗳️ Votar en las votaciones (torneo, Battle Royale)\n• 🏆 Ver sus propias puntuaciones y logros',
  'tutorial.companion.steps.soloQueue.title': 'Peticiones sin control',
  'tutorial.companion.steps.soloQueue.body': 'También sin mando, cada invitado encola sus propias canciones: elige una en el teléfono, encola — listo. La petición llega aquí con la insignia 📱 y cuenta para el límite de 3 canciones del perfil.',
  'tutorial.companion.steps.soloParty.title': 'Cantar y votar',
  'tutorial.companion.steps.soloParty.body': 'La participación en la fiesta pasa siempre por los teléfonos: en Companion Sing-A-Long y Pasa el Micrófono los invitados cantan directamente desde su dispositivo, en el torneo y en Battle Royale votan con un toque — todo sin Take Control.',
  'tutorial.companion.steps.soloStats.title': 'Logros y puntuaciones propios',
  'tutorial.companion.steps.soloStats.body': 'Cada invitado lleva su propio álbum: en el teléfono puede ver sus puntuaciones y logros — sin Take Control. Lo que el perfil consigue, el invitado lo comprueba incluso desde el sofá.',
  'tutorial.companion.steps.soloLimits.title': 'Lo que sigue bloqueado',
  'tutorial.companion.steps.soloLimits.body': 'Sin control, los ajustes, los perfiles, la configuración de fiesta, los retos diarios y la Jukebox quedan fuera — siguen reservados al escritorio (o a un Companion con Take Control).',
  'tutorial.companion.steps.soloLimits.details': '¿Por qué el candado? Estas áreas cambian el estado o la configuración de la partida para todos: ajustes, gestión de perfiles, configuración de fiesta, retos diarios y Jukebox. Para eso existe el control explícito — "Tomar control" los desbloquea para exactamente un teléfono.\n\nEl anfitrión del escritorio siempre lo tiene todo en su mano.',
  'tutorial.companion.steps.helpButton.title': 'Ayuda en cada teléfono ❓',
  'tutorial.companion.steps.helpButton.body': 'Conoces el menú ? de la barra de menú — cada teléfono conectado recibe su propio botón "?". Un toque abre la ayuda del Companion directamente en el dispositivo.',
  'tutorial.companion.steps.helpLocal.title': 'Solo leer, nunca controlar',
  'tutorial.companion.steps.helpLocal.body': 'La ayuda del Companion es una vista puramente de lectura: no envía comandos al escritorio y nunca inicia un tour del escritorio. Los invitados pueden abrirla en cualquier momento — incluso mientras alguien canta o controla.',
  'tutorial.companion.steps.helpLocal.details': 'Así, la ayuda queda deliberadamente separada del sistema de control: un invitado que solo quiere consultar algo ("¿Cómo encolo una canción?") no influye para nada en la noche en marcha — y los tours aquí en el escritorio siguen siendo cosa del anfitrión.\n\nSe abre con el botón "?" de la app compañera; se cierra simplemente cerrando la vista.',
}

# ─────────────────────────────── FRANÇAIS (vous) ───────────────────────────────
T['fr'] = {
  'mobile.toastControlAcquired': 'Contrôle pris',
  'mobile.toastControlReleased': 'Contrôle libéré',
  'mobile.toastControlLost': 'Contrôle perdu',
  'mobile.toastControlTaken': 'Contrôle déjà pris',
  'mobile.toastLockedNav': 'Contrôle à distance requis',
  'mobile.homeControlYouTitle': 'Vous contrôlez le bureau',
  'mobile.homeControlYouDesc': 'Vos onglets pilotent le bureau — toutes les zones sont déverrouillées.',
  'mobile.homeCurrentSong': 'Chanson en cours',
  'mobile.homeHotkeysTitle': 'Raccourcis du bureau',
  'mobile.homeHotkeysDesc': 'Les raccourcis clavier les plus importants du bureau',
  'mobile.homeRequestSong': 'Demander une chanson',
  'mobile.homeTakeControlForFull': 'Prenez le contrôle pour un accès complet',
  'mobile.homeControlByTitle': 'Contrôle aux mains de {name}',
  'mobile.homeControlFreeTitle': 'Aucun contrôle actif',
  'mobile.homeControlHintDesc': 'Sans contrôle, vous pouvez demander des chansons, chatter et participer.',
  'mobile.mirrorSettingsSubtitle': 'Contrôlez les paramètres du bureau en direct depuis votre téléphone',
  'mobile.mirrorSettingsNoSnapshot': 'Valeurs du bureau pas encore reçues — valeurs par défaut affichées',
  'mobile.mirrorSettingsNeedControl': 'Prenez le contrôle à distance pour envoyer des modifications au bureau',
  'mobile.mirrorSettingsWebcamNone': 'Aucune webcam n\'est encore configurée sur le bureau. Activez-la ici pour créer une configuration par défaut.',
  'mobile.mirrorSettingsWebcamSent': 'Les modifications sont enregistrées sur le bureau et prendront effet à la prochaine chanson.',
  'mobile.mirrorLoadError': 'Impossible de charger les données.',
  'mobile.mirrorRetry': 'Réessayer',
  'mobile.mirrorNoProfileLink': 'Aucun profil lié. Connectez l\'app compagnon à un profil pour voir vos données.',
  'mobile.mirrorProfileMissing': 'Votre profil est introuvable sur le bureau. Vos succès apparaîtront ici dès que le profil du bureau sera synchronisé.',
  'mobile.mirrorOnlyMine': 'Seulement les miens',
  'mobile.mirrorAll': 'Tous',
  'mobile.mirrorEntries': '{n} entrées',
  'mobile.mirrorDailyNoData': 'Aucune donnée quotidienne pour votre profil.',
  'mobile.mirrorDailyControlHint': 'Affichage seul — prenez le contrôle pour lancer des défis.',
  'mobile.mirrorDailyModesHint': 'Les modes défi se jouent sur le bureau — voici le catalogue.',
  'mobile.mirrorSlotsToday': '{n}/{m} emplacements aujourd\'hui',
  'mobile.mirrorPlayer': 'Joueur',
  'mobile.mirrorProfileYou': 'Vous',
  'mobile.mirrorProfileControlHint': 'Affichage seul — prenez le contrôle pour activer ou désactiver des profils.',
  'mobile.mirrorSongsShort': 'Chansons',
  'mobile.mirrorJukeboxFilters': 'Filtres',
  'mobile.mirrorJukeboxFilterSet': 'Définir les filtres',
  'mobile.mirrorJukeboxFilterRemove': 'Retirer le filtre',
  'mobile.mirrorJukeboxNoFilters': 'Aucun filtre actif — la Jukebox joue depuis tout le pool.',
  'mobile.mirrorJukeboxFilterGenre': 'Genre',
  'mobile.mirrorJukeboxFilterArtist': 'Artiste',
  'mobile.mirrorJukeboxFilterEra': 'Décennie',
  'mobile.mirrorJukeboxFilterYear': 'Année',
  'mobile.mirrorJukeboxFilterAllArtists': 'Tous les artistes',
  'mobile.mirrorJukeboxFilterAllEras': 'Toutes les décennies',
  'mobile.mirrorJukeboxFilterAllYears': 'Toutes les années',
  'mobile.mirrorJukeboxFilterApplied': 'Filtre appliqué — prend effet sur le bureau.',
  'mobile.mirrorJukeboxFilterCleared': 'Filtre retiré.',
  'mobile.mirrorJukeboxNoLibrary': 'Chargement de la bibliothèque…',
  'mobile.mirrorJukeboxStateChipPool': 'Pool',
  'mobile.mirrorJukeboxPoolAll': 'Toutes les chansons',
  'mobile.mirrorJukeboxPlaylistsTitle': 'Playlists et pool',
  'mobile.mirrorJukeboxPlaylistSongs': '{n} chansons',
  'mobile.mirrorJukeboxSystemBadge': 'Système',
  'mobile.mirrorJukeboxSetPool': 'Définir comme pool',
  'mobile.mirrorJukeboxActivePool': 'Pool actif',
  'mobile.mirrorJukeboxPoolSet': 'Pool de chansons défini.',
  'mobile.mirrorJukeboxPoolCleared': 'Pool de chansons réinitialisé — toutes les chansons.',
  'mobile.mirrorJukeboxEnqueue': 'Vers la liste de souhaits',
  'mobile.mirrorJukeboxEnqueueConfirm': 'Mettre en file ?',
  'mobile.mirrorJukeboxEnqueued': 'Playlist mise en file — bientôt jouée sur le bureau.',
  'mobile.mirrorJukeboxPlaylistsEmpty': 'Aucune playlist pour le moment.',
  'mobile.mirrorJukeboxPlaylistsError': 'Impossible de charger les playlists.',
  'mobile.mirrorJukeboxRefresh': 'Actualiser',
  'mobile.mirrorJukeboxRequestedBy': 'par',
  'mobile.mirrorQueueEmptyTitle': 'Aucune demande pour le moment',
  'mobile.mirrorQueueEmptyBrowse': 'Parcourez la bibliothèque et choisissez une chanson !',
  'mobile.mirrorQueueDesktopControls': 'Le bureau décide quand on chante',
  'mobile.queueSlotsFull': 'Tous les emplacements sont occupés',
  'mobile.hotkeys.cardTitle': 'Raccourcis clavier',
  'mobile.hotkeys.cardHint': 'Les raccourcis les plus importants pour le bureau',
  'mobile.hotkeys.collapse': 'Replier les raccourcis clavier',
  'mobile.hotkeys.expand': 'Déplier les raccourcis clavier',
  'mobile.hotkeys.esc': 'Pause / retour / annuler',
  'mobile.hotkeys.enter': 'Reprendre (en pause)',
  'mobile.hotkeys.f12': 'Activer/désactiver le plein écran',
  'mobile.hotkeys.ctrlL': 'Focus sur la recherche de la bibliothèque',
  'mobile.hotkeys.ctrlR': 'Chanson aléatoire (solo)',
  'mobile.hotkeys.ctrlD': 'Chanson aléatoire (duel)',
  'mobile.hotkeys.ctrlQ': 'Jouer la chanson suivante de la file',
  'mobile.hotkeys.ctrlJ': 'Ouvrir la Jukebox',
  'mobile.hotkeys.fkeys': 'Aller directement aux écrans : F1 Accueil · F2 Bibliothèque · F3 Fête · F4 File · F5 Profils · F6 Scores · F7 Succès · F8 Jukebox · F9 Paramètres · F10 Éditeur',
  'mobileHelp.title': 'Aide',
  'mobileHelp.close': 'Fermer',
  'mobileHelp.intro': 'App Companion : tout sur la connexion, le contrôle à distance, la participation et le chant — en cinq chapitres courts.',
  'mobileHelp.ch1Title': 'Connexion et microphone',
  'mobileHelp.ch1b1': 'Scannez le QR code sur le bureau ou ouvrez le lien Companion — le téléphone et le PC doivent être sur le même réseau WiFi.',
  'mobileHelp.ch1b2': 'Créez un profil (nom, couleur, photo) — il se synchronise automatiquement avec le bureau.',
  'mobileHelp.ch1b3': 'La première fois que vous chantez, le navigateur demande l\'accès au micro — touchez "Autoriser".',
  'mobileHelp.ch1b4': 'Le code en haut à droite de l\'en-tête indique que la connexion est établie.',
  'mobileHelp.ch2Title': 'Contrôle à distance : prendre le contrôle',
  'mobileHelp.ch2b1': 'Avec "Prendre le contrôle", votre téléphone reflète l\'écran du bureau — vous voyez toujours ce qui tourne sur le PC.',
  'mobileHelp.ch2b2': 'Votre barre d\'onglets pilote alors le bureau : accueil, bibliothèque, fête, file, Jukebox, scores, succès, paramètres.',
  'mobileHelp.ch2b3': 'Depuis la page d\'accueil, vous pouvez mettre en pause ou passer la chanson en cours.',
  'mobileHelp.ch2b4': 'Un SEUL appareil contrôle à la fois — "Libérer le contrôle" libère la place.',
  'mobileHelp.ch3Title': 'Sans contrôle',
  'mobileHelp.ch3b1': 'Demander des chansons : ouvrez la bibliothèque, touchez une chanson, choisissez vos options (mode, difficulté, micro) et ajoutez-la à la file — jusqu\'à 3 chansons.',
  'mobileHelp.ch3b2': 'Chat : touchez 💬 en haut à droite et échangez avec l\'hôte et les autres joueurs.',
  'mobileHelp.ch3b3': 'Fête : vous votez dans les scrutins de chansons, voyez les signaux de tour et chantez quand c\'est votre tour — tout par overlays, sans contrôle nécessaire.',
  'mobileHelp.ch3b4': 'Vos propres succès et scores se trouvent dans la barre d\'onglets (🏅 succès, 🏆 scores).',
  'mobileHelp.ch3b5': 'Les zones avec cadenas (paramètres, profils, fête, défi, Jukebox) nécessitent le contrôle à distance — votre propre profil reste toujours modifiable.',
  'mobileHelp.ch4Title': 'Chanter avec le téléphone',
  'mobileHelp.ch4b1': 'Quand c\'est votre tour dans le jeu, le micro démarre automatiquement — en Battle Royale, tout le monde chante en même temps.',
  'mobileHelp.ch4b2': 'La barre fine sous l\'en-tête affiche le volume et la note détectée de votre chant.',
  'mobileHelp.ch4b3': 'Tenez le téléphone près de la bouche et éloignez la musique des haut-parleurs de l\'appareil.',
  'mobileHelp.ch5Title': 'Dépannage',
  'mobileHelp.ch5b1': 'Connexion perdue : l\'app se reconnecte automatiquement. Sinon, vérifiez le WiFi et touchez "Réessayer la Connexion".',
  'mobileHelp.ch5b2': 'Pas de micro/son : vérifiez l\'autorisation du micro dans les paramètres du site du navigateur.',
  'mobileHelp.ch5b3': 'Le miroir reste vide : le bureau (l\'app PC) doit être en marche et sur le même réseau.',
  'mobileHelp.ch5b4': 'Le contrôle ne répond pas : un autre appareil détient le contrôle — la carte d\'état de la page d\'accueil indique qui contrôle.',
  'mobileHelp.localOnlyNote': 'Cette aide tourne entièrement sur votre téléphone — elle ne contrôle pas le bureau.',
  'mobileViews.desktopDefaultDifficulty': 'Par défaut du bureau',
  'mobileViews.queueAddAction': 'Ajouter à la file',
  'settings.loudnessNormalization': 'Normalisation du volume (cible : 89 dB)',
  'tutorial.companion.chapters.control': 'Contrôle à distance : Take Control',
  'tutorial.companion.chapters.solo': 'Sans contrôle',
  'tutorial.companion.chapters.help': 'Aide du Companion',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': 'Un téléphone ne pilote désormais le bureau que sur commande : le bouton "Prendre le contrôle" du Companion s\'empare de la télécommande — avant et après, le téléphone ne tape que pour lui-même.',
  'tutorial.companion.steps.takeControl.details': 'Le mécanisme derrière "Prendre le contrôle" :\n• Le contrôle est réservé exclusivement à un seul appareil (verrou distant).\n• Le bureau et le téléphone qui contrôle restent synchronisés : chaque côté voit instantanément ce que fait l\'autre.\n• Tous les autres téléphones affichent le statut "Contrôlé par …" et attendent.\n\nLe contrôle se termine via "Libérer" — ou automatiquement si le téléphone perd la connexion.',
  'tutorial.companion.steps.controlSync.title': 'Bureau et téléphone en synchro',
  'tutorial.companion.steps.controlSync.body': 'Retour dans l\'onglet Mobile : en tant qu\'hôte, vous voyez ici tous les appareils. Quand un téléphone prend le contrôle, il reflète l\'écran du bureau et actionne écrans, boutons et confirmations — souris et clavier du bureau restent pleinement utilisables.',
  'tutorial.companion.steps.controlSync.details': 'Comme les deux côtés tournent en synchro, personne ne peut "taper en avançant" : cliquez sur le bureau et le téléphone qui contrôle suit — touchez le téléphone et le bureau change d\'écran.\n\nDans la liste des appareils, vous reconnaissez l\'appareil qui contrôle à son badge de télécommande.',
  'tutorial.companion.steps.controlHandover.title': 'Une seule télécommande à la fois',
  'tutorial.companion.steps.controlHandover.body': 'Le contrôle est exclusif : pendant qu\'un téléphone pilote, aucun second ne peut prendre la main — son bouton indique plutôt qui contrôle. Libérer ou se déconnecter rend le contrôle instantanément.',
  'tutorial.companion.steps.controlHandover.details': 'Bon à savoir :\n• L\'hôte peut continuer à cliquer à tout moment — le téléphone qui contrôle suit (et garde le contrôle).\n• Si le téléphone qui contrôle perd la connexion (batterie, WiFi), le contrôle revient automatiquement au bureau.\n• Un renvoi depuis la liste des appareils met aussi fin au contrôle.',
  'tutorial.companion.steps.soloOverview.title': 'Invités sans contrôle 🙋',
  'tutorial.companion.steps.soloOverview.body': 'La plupart des invités n\'ont jamais besoin de la télécommande : les téléphones connectés sans Take Control sont des compagnons autonomes — ils demandent des chansons, discutent, chantent et consultent leurs propres succès sans toucher au bureau.',
  'tutorial.companion.steps.soloOverview.details': 'Ce que peuvent faire les téléphones sans contrôle :\n• 🎵 Mettre leurs propres chansons en file (avec le badge 📱)\n• 💬 Rejoindre le chat de la fête\n• 🎤 Chanter dans les modes fête (Companion Sing-A-Long, Passe le Micro)\n• 🗳️ Voter aux scrutins (tournoi, Battle Royale)\n• 🏆 Consulter leurs propres scores et succès',
  'tutorial.companion.steps.soloQueue.title': 'Demandes sans contrôle',
  'tutorial.companion.steps.soloQueue.body': 'Même sans télécommande, chaque invité met ses propres chansons en file : choisir une chanson sur le téléphone, la mettre en file — terminé. La demande arrive ici avec le badge 📱 et compte dans la limite de 3 chansons du profil.',
  'tutorial.companion.steps.soloParty.title': 'Chanter et voter',
  'tutorial.companion.steps.soloParty.body': 'La participation à la fête passe toujours par les téléphones : en Companion Sing-A-Long et Passe le Micro, les invités chantent directement sur leur appareil ; au tournoi et en Battle Royale, ils votent d\'un geste — le tout sans Take Control.',
  'tutorial.companion.steps.soloStats.title': 'Succès et scores personnels',
  'tutorial.companion.steps.soloStats.body': 'Chaque invité garde son propre album : sur le téléphone, il peut consulter ses scores et ses succès — sans Take Control. Ce que le profil gagne, l\'invité peut le vérifier depuis le canapé.',
  'tutorial.companion.steps.soloLimits.title': 'Ce qui reste verrouillé',
  'tutorial.companion.steps.soloLimits.body': 'Sans contrôle, paramètres, profils, configuration de la fête, défis quotidiens et Jukebox restent hors d\'atteinte — ils demeurent réservés au bureau (ou à un Companion avec Take Control).',
  'tutorial.companion.steps.soloLimits.details': 'Pourquoi le cadenas ? Ces zones modifient l\'état du jeu ou la configuration pour tous : paramètres, gestion des profils, configuration de la fête, défis quotidiens et Jukebox. C\'est à cela que sert le contrôle explicite — "Prendre le contrôle" les déverrouille pour exactement un téléphone.\n\nL\'hôte du bureau garde toujours tout en main.',
  'tutorial.companion.steps.helpButton.title': 'De l\'aide sur chaque téléphone ❓',
  'tutorial.companion.steps.helpButton.body': 'Vous connaissez le menu ? ici dans la barre de menu — chaque téléphone connecté reçoit son propre bouton "?". Un geste ouvre l\'aide du Companion directement sur l\'appareil.',
  'tutorial.companion.steps.helpLocal.title': 'Lecture seule, jamais de contrôle',
  'tutorial.companion.steps.helpLocal.body': 'L\'aide du Companion est une pure vue de lecture : elle n\'envoie aucune commande au bureau et ne lance jamais une visite du bureau. Les invités peuvent l\'ouvrir à tout moment — même pendant que quelqu\'un chante ou contrôle.',
  'tutorial.companion.steps.helpLocal.details': 'L\'aide est volontairement tenue à l\'écart du système de contrôle : un invité qui veut juste vérifier un point ("Comment mettre une chanson en file ?") n\'a aucune influence sur la soirée en cours — et les visites ici sur le bureau restent votre affaire d\'hôte.\n\nOuvrez-la via le bouton "?" de l\'app compagnon ; fermez-la simplement en fermant la vue.',
}

# ─────────────────────────────── ITALIANO (tu) ───────────────────────────────
T['it'] = {
  'mobile.toastControlAcquired': 'Controllo acquisito',
  'mobile.toastControlReleased': 'Controllo rilasciato',
  'mobile.toastControlLost': 'Controllo perso',
  'mobile.toastControlTaken': 'Controllo già assegnato',
  'mobile.toastLockedNav': 'Solo con controllo remoto',
  'mobile.homeControlYouTitle': 'Tu controlli il desktop',
  'mobile.homeControlYouDesc': 'Le tue tab guidano il desktop — tutte le aree sono sbloccate.',
  'mobile.homeCurrentSong': 'Canzone attuale',
  'mobile.homeHotkeysTitle': 'Scorciatoie del desktop',
  'mobile.homeHotkeysDesc': 'Le scorciatoie da tastiera più importanti del desktop',
  'mobile.homeRequestSong': 'Richiedi una canzone',
  'mobile.homeTakeControlForFull': 'Prendi il controllo per l\'accesso completo',
  'mobile.homeControlByTitle': 'Controllo in mano a {name}',
  'mobile.homeControlFreeTitle': 'Nessun controllo attivo',
  'mobile.homeControlHintDesc': 'Senza controllo puoi richiedere canzoni, chattare e partecipare.',
  'mobile.mirrorSettingsSubtitle': 'Controlla le impostazioni del desktop in diretta dal telefono',
  'mobile.mirrorSettingsNoSnapshot': 'Valori del desktop non ancora ricevuti — vengono mostrati quelli predefiniti',
  'mobile.mirrorSettingsNeedControl': 'Prendi il controllo remoto per inviare modifiche al desktop',
  'mobile.mirrorSettingsWebcamNone': 'Sul desktop non è ancora configurata nessuna webcam. Attivala qui per creare una configurazione predefinita.',
  'mobile.mirrorSettingsWebcamSent': 'Le modifiche vengono salvate sul desktop e valgono dalla canzone successiva.',
  'mobile.mirrorLoadError': 'Impossibile caricare i dati.',
  'mobile.mirrorRetry': 'Riprova',
  'mobile.mirrorNoProfileLink': 'Nessun profilo collegato. Collega l\'app Companion a un profilo per vedere i tuoi dati.',
  'mobile.mirrorProfileMissing': 'Il tuo profilo non è stato trovato sul desktop. I tuoi risultati compariranno qui appena il profilo del desktop si sincronizza.',
  'mobile.mirrorOnlyMine': 'Solo i miei',
  'mobile.mirrorAll': 'Tutti',
  'mobile.mirrorEntries': '{n} voci',
  'mobile.mirrorDailyNoData': 'Nessun dato giornaliero per il tuo profilo.',
  'mobile.mirrorDailyControlHint': 'Solo visualizzazione — prendi il controllo per avviare le sfide.',
  'mobile.mirrorDailyModesHint': 'Le modalità sfida si giocano sul desktop — questo è il catalogo.',
  'mobile.mirrorSlotsToday': '{n}/{m} slot di oggi',
  'mobile.mirrorPlayer': 'Giocatore',
  'mobile.mirrorProfileYou': 'Tu',
  'mobile.mirrorProfileControlHint': 'Solo visualizzazione — prendi il controllo per attivare o disattivare i profili.',
  'mobile.mirrorSongsShort': 'Canzoni',
  'mobile.mirrorJukeboxFilters': 'Filtri',
  'mobile.mirrorJukeboxFilterSet': 'Imposta filtri',
  'mobile.mirrorJukeboxFilterRemove': 'Rimuovi filtro',
  'mobile.mirrorJukeboxNoFilters': 'Nessun filtro attivo — la Jukebox suona da tutto il repertorio.',
  'mobile.mirrorJukeboxFilterGenre': 'Genere',
  'mobile.mirrorJukeboxFilterArtist': 'Artista',
  'mobile.mirrorJukeboxFilterEra': 'Decennio',
  'mobile.mirrorJukeboxFilterYear': 'Anno',
  'mobile.mirrorJukeboxFilterAllArtists': 'Tutti gli artisti',
  'mobile.mirrorJukeboxFilterAllEras': 'Tutti i decenni',
  'mobile.mirrorJukeboxFilterAllYears': 'Tutti gli anni',
  'mobile.mirrorJukeboxFilterApplied': 'Filtro impostato — ha effetto sul desktop.',
  'mobile.mirrorJukeboxFilterCleared': 'Filtro rimosso.',
  'mobile.mirrorJukeboxNoLibrary': 'Caricamento libreria…',
  'mobile.mirrorJukeboxStateChipPool': 'Repertorio',
  'mobile.mirrorJukeboxPoolAll': 'Tutte le canzoni',
  'mobile.mirrorJukeboxPlaylistsTitle': 'Playlist e repertorio',
  'mobile.mirrorJukeboxPlaylistSongs': '{n} canzoni',
  'mobile.mirrorJukeboxSystemBadge': 'Sistema',
  'mobile.mirrorJukeboxSetPool': 'Imposta come repertorio',
  'mobile.mirrorJukeboxActivePool': 'Repertorio attivo',
  'mobile.mirrorJukeboxPoolSet': 'Repertorio di canzoni impostato.',
  'mobile.mirrorJukeboxPoolCleared': 'Repertorio ripristinato — tutte le canzoni.',
  'mobile.mirrorJukeboxEnqueue': 'Alla lista dei desideri',
  'mobile.mirrorJukeboxEnqueueConfirm': 'Mettere in coda?',
  'mobile.mirrorJukeboxEnqueued': 'Playlist in coda — tra poco parte sul desktop.',
  'mobile.mirrorJukeboxPlaylistsEmpty': 'Ancora nessuna playlist.',
  'mobile.mirrorJukeboxPlaylistsError': 'Impossibile caricare le playlist.',
  'mobile.mirrorJukeboxRefresh': 'Aggiorna',
  'mobile.mirrorJukeboxRequestedBy': 'di',
  'mobile.mirrorQueueEmptyTitle': 'Ancora nessuna richiesta',
  'mobile.mirrorQueueEmptyBrowse': 'Sfoglia la libreria e scegli una canzone!',
  'mobile.mirrorQueueDesktopControls': 'Il desktop decide quando si canta',
  'mobile.queueSlotsFull': 'Tutti i posti occupati',
  'mobile.hotkeys.cardTitle': 'Scorciatoie da tastiera',
  'mobile.hotkeys.cardHint': 'Le scorciatoie più importanti per il desktop',
  'mobile.hotkeys.collapse': 'Comprimi le scorciatoie da tastiera',
  'mobile.hotkeys.expand': 'Espandi le scorciatoie da tastiera',
  'mobile.hotkeys.esc': 'Pausa / indietro / annulla',
  'mobile.hotkeys.enter': 'Riprendi (in pausa)',
  'mobile.hotkeys.f12': 'Attiva/disattiva schermo intero',
  'mobile.hotkeys.ctrlL': 'Focalizza la ricerca della libreria',
  'mobile.hotkeys.ctrlR': 'Canzone casuale (singolo)',
  'mobile.hotkeys.ctrlD': 'Canzone casuale (duello)',
  'mobile.hotkeys.ctrlQ': 'Riproduci la prossima canzone della coda',
  'mobile.hotkeys.ctrlJ': 'Apri la Jukebox',
  'mobile.hotkeys.fkeys': 'Vai diretto alle schermate: F1 Home · F2 Libreria · F3 Festa · F4 Coda · F5 Profili · F6 Punteggi · F7 Obiettivi · F8 Jukebox · F9 Impostazioni · F10 Editor',
  'mobileHelp.title': 'Aiuto',
  'mobileHelp.close': 'Chiudi',
  'mobileHelp.intro': 'App Companion: tutto su connessione, controllo remoto, partecipazione e canto — in cinque capitoli brevi.',
  'mobileHelp.ch1Title': 'Connessione e microfono',
  'mobileHelp.ch1b1': 'Scansiona il QR code sul desktop o apri il link Companion — telefono e PC devono essere nella stessa rete WiFi.',
  'mobileHelp.ch1b2': 'Crea un profilo (nome, colore, foto) — si sincronizza automaticamente con il desktop.',
  'mobileHelp.ch1b3': 'La prima volta che canti, il browser chiede l\'accesso al microfono — tocca "Consenti".',
  'mobileHelp.ch1b4': 'Il codice in alto a destra dell\'header indica che la connessione è attiva.',
  'mobileHelp.ch2Title': 'Controllo remoto: prendere il controllo',
  'mobileHelp.ch2b1': 'Con "Prendi il controllo" il tuo telefono rispecchia lo schermo del desktop — vedi sempre cosa gira sul PC.',
  'mobileHelp.ch2b2': 'La tua barra delle tab guida quindi il desktop: home, libreria, festa, coda, Jukebox, punteggi, risultati, impostazioni.',
  'mobileHelp.ch2b3': 'Dalla pagina iniziale puoi mettere in pausa o saltare la canzone in corso.',
  'mobileHelp.ch2b4': 'Solo UN dispositivo controlla alla volta — "Rilascia controllo" libera il posto.',
  'mobileHelp.ch3Title': 'Senza controllo',
  'mobileHelp.ch3b1': 'Richiedere canzoni: apri la libreria, tocca una canzone, scegli le opzioni (modalità, difficoltà, micro) e aggiungila alla coda — fino a 3 canzoni.',
  'mobileHelp.ch3b2': 'Chat: tocca 💬 in alto a destra e parla con l\'host e gli altri giocatori.',
  'mobileHelp.ch3b3': 'Festa: voti nelle votazioni delle canzoni, vedi i segnali di turno e canti quando tocca a te — tutto tramite overlay, senza bisogno di controllo.',
  'mobileHelp.ch3b4': 'I tuoi risultati e punteggi li trovi nella barra delle tab (🏅 risultati, 🏆 punteggi).',
  'mobileHelp.ch3b5': 'Le aree con lucchetto (impostazioni, profili, festa, sfida, Jukebox) richiedono il controllo remoto — il tuo profilo puoi sempre modificarlo.',
  'mobileHelp.ch4Title': 'Cantare con il telefono',
  'mobileHelp.ch4b1': 'Quando arriva il tuo turno nel gioco, il microfono si avvia automaticamente — in Battle Royale cantano tutti insieme.',
  'mobileHelp.ch4b2': 'La barra sottile sotto l\'header mostra il volume e la nota rilevata del tuo canto.',
  'mobileHelp.ch4b3': 'Tieni il telefono vicino alla bocca e tieni la musica degli altoparlanti lontana dal dispositivo.',
  'mobileHelp.ch5Title': 'Risoluzione dei problemi',
  'mobileHelp.ch5b1': 'Connessione persa: l\'app si riconnette automaticamente. Altrimenti controlla la WiFi e tocca "Riprova Connessione".',
  'mobileHelp.ch5b2': 'Niente microfono/audio: controlla il permesso del microfono nelle impostazioni del sito del browser.',
  'mobileHelp.ch5b3': 'Lo specchio resta vuoto: il desktop (l\'app PC) deve essere in esecuzione e nella stessa rete.',
  'mobileHelp.ch5b4': 'Il controllo non risponde: un altro dispositivo ha il controllo — la card di stato nella pagina iniziale mostra chi controlla.',
  'mobileHelp.localOnlyNote': 'Questo aiuto gira interamente sul tuo telefono — non controlla il desktop.',
  'mobileViews.desktopDefaultDifficulty': 'Predefinito del desktop',
  'mobileViews.queueAddAction': 'Aggiungi alla coda',
  'settings.loudnessNormalization': 'Normalizzazione del volume (obiettivo 89 dB)',
  'tutorial.companion.chapters.control': 'Controllo remoto: Take Control',
  'tutorial.companion.chapters.solo': 'Senza controllo',
  'tutorial.companion.chapters.help': 'Aiuto del Companion',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': 'Un telefono ora guida il desktop solo su comando: il pulsante "Prendi il controllo" sul Companion si prende il telecomando — prima e dopo, il telefono tocca solo per sé.',
  'tutorial.companion.steps.takeControl.details': 'Il meccanismo dietro "Prendi il controllo":\n• Il controllo è riservato in esclusiva a un solo dispositivo (blocco remoto).\n• Desktop e telefono che controlla restano sincronizzati: ogni lato vede subito cosa fa l\'altro.\n• Tutti gli altri telefoni mostrano lo stato "Controllato da …" e aspettano.\n\nIl controllo termina con "Rilascia" — o automaticamente se il telefono perde la connessione.',
  'tutorial.companion.steps.controlSync.title': 'Desktop e telefono in sincrono',
  'tutorial.companion.steps.controlSync.body': 'Torniamo nella scheda Mobile: qui da host vedi tutti i dispositivi. Quando un telefono prende il controllo, rispecchia lo schermo del desktop e comanda schermate, pulsanti e conferme — mouse e tastiera sul desktop restano pienamente utilizzabili.',
  'tutorial.companion.steps.controlSync.details': 'Poiché entrambi i lati girano in sincrono, nessuno può "toccare e scappare": clicchi sul desktop e il telefono che controlla segue — tocchi sul telefono e il desktop cambia schermata.\n\nNella lista dei dispositivi riconosci il dispositivo che controlla dal badge del telecomando.',
  'tutorial.companion.steps.controlHandover.title': 'Un solo telecomando alla volta',
  'tutorial.companion.steps.controlHandover.body': 'Il controllo è esclusivo: mentre un telefono guida, nessun secondo può subentrare — il suo pulsante mostra invece chi sta controllando. Rilasciare o disconnettersi libera subito il controllo.',
  'tutorial.companion.steps.controlHandover.details': 'Buono a sapersi:\n• L\'host può continuare a cliccare quando vuole — il telefono che controlla segue (e mantiene il controllo).\n• Se il telefono che controlla perde la connessione (batteria, WiFi), il controllo torna automaticamente al desktop.\n• Anche un kick dalla lista dei dispositivi termina il controllo.',
  'tutorial.companion.steps.soloOverview.title': 'Ospiti senza controllo 🙋',
  'tutorial.companion.steps.soloOverview.body': 'La maggior parte degli ospiti non ha mai bisogno del telecomando: i telefoni connessi senza Take Control sono compagni autonomi — richiedono canzoni, chattano, cantano e consultano i propri risultati senza toccare il desktop.',
  'tutorial.companion.steps.soloOverview.details': 'Cosa possono fare i telefoni senza controllo:\n• 🎵 Mettere in coda le proprie canzoni (con il badge 📱)\n• 💬 Entrare nella chat della festa\n• 🎤 Cantare nelle modalità festa (Companion Sing-A-Long, Passa il Microfono)\n• 🗳️ Votare nei sondaggi (torneo, Battle Royale)\n• 🏆 Vedere i propri punteggi e risultati',
  'tutorial.companion.steps.soloQueue.title': 'Richieste senza controllo',
  'tutorial.companion.steps.soloQueue.body': 'Anche senza telecomando ogni ospite mette in coda le proprie canzoni: scegli una canzone sul telefono, mettila in coda — fatto. La richiesta arriva qui con il badge 📱 e conta per il limite di 3 canzoni del profilo.',
  'tutorial.companion.steps.soloParty.title': 'Cantare e votare',
  'tutorial.companion.steps.soloParty.body': 'La partecipazione alla festa passa sempre dai telefoni: in Companion Sing-A-Long e Passa il Microfono gli ospiti cantano direttamente dal dispositivo, al torneo e in Battle Royale votano con un tocco — tutto senza Take Control.',
  'tutorial.companion.steps.soloStats.title': 'Risultati e punteggi propri',
  'tutorial.companion.steps.soloStats.body': 'Ogni ospite ha il proprio album: sul telefono può consultare i propri punteggi e risultati — senza Take Control. Ciò che il profilo conquista, l\'ospite lo verifica anche dal divano.',
  'tutorial.companion.steps.soloLimits.title': 'Cosa resta bloccato',
  'tutorial.companion.steps.soloLimits.body': 'Senza controllo, impostazioni, profili, configurazione della festa, sfide giornaliere e Jukebox restano fuori — restano riservati al desktop (o a un Companion con Take Control).',
  'tutorial.companion.steps.soloLimits.details': 'Perché il lucchetto? Queste aree cambiano lo stato di gioco o la configurazione per tutti: impostazioni, gestione dei profili, configurazione della festa, sfide giornaliere e Jukebox. Per questo esiste il controllo esplicito — "Prendi il controllo" li sblocca per esattamente un telefono.\n\nL\'host del desktop ha sempre tutto in mano.',
  'tutorial.companion.steps.helpButton.title': 'Aiuto su ogni telefono ❓',
  'tutorial.companion.steps.helpButton.body': 'Conosci il menu ? qui nella barra dei menu — ogni telefono connesso riceve il proprio pulsante "?". Un tocco apre l\'aiuto del Companion direttamente sul dispositivo.',
  'tutorial.companion.steps.helpLocal.title': 'Solo leggere, mai controllare',
  'tutorial.companion.steps.helpLocal.body': 'L\'aiuto del Companion è una pura vista di lettura: non invia comandi al desktop e non avvia mai un tour del desktop. Gli ospiti possono aprirlo in qualsiasi momento — anche mentre qualcuno canta o controlla.',
  'tutorial.companion.steps.helpLocal.details': 'Così l\'aiuto resta volutamente separato dal sistema di controllo: un ospite che vuole solo controllare una cosa ("Come metto in coda una canzone?") non influenza affatto la serata in corso — e i tour qui sul desktop restano affare dell\'host.\n\nSi apre con il pulsante "?" nell\'app Companion; si chiude semplicemente chiudendo la vista.',
}

# ─────────────────────────────── PORTUGUÊS (você) ───────────────────────────────
T['pt'] = {
  'mobile.toastControlAcquired': 'Controle assumido',
  'mobile.toastControlReleased': 'Controle liberado',
  'mobile.toastControlLost': 'Controle perdido',
  'mobile.toastControlTaken': 'Controle já assumido',
  'mobile.toastLockedNav': 'Somente com controle remoto',
  'mobile.homeControlYouTitle': 'Você controla o desktop',
  'mobile.homeControlYouDesc': 'Suas abas comandam o desktop — todas as áreas estão desbloqueadas.',
  'mobile.homeCurrentSong': 'Música atual',
  'mobile.homeHotkeysTitle': 'Atalhos do desktop',
  'mobile.homeHotkeysDesc': 'Os atalhos de teclado mais importantes do desktop',
  'mobile.homeRequestSong': 'Pedir uma música',
  'mobile.homeTakeControlForFull': 'Assuma o controle para acesso total',
  'mobile.homeControlByTitle': 'Controle nas mãos de {name}',
  'mobile.homeControlFreeTitle': 'Nenhum controle ativo',
  'mobile.homeControlHintDesc': 'Sem controle você pode pedir músicas, conversar no chat e participar.',
  'mobile.mirrorSettingsSubtitle': 'Controle as definições do desktop ao vivo pelo seu telefone',
  'mobile.mirrorSettingsNoSnapshot': 'Valores do desktop ainda não recebidos — mostrando valores predefinidos',
  'mobile.mirrorSettingsNeedControl': 'Assuma o controle remoto para enviar alterações ao desktop',
  'mobile.mirrorSettingsWebcamNone': 'Ainda não há webcam configurada no desktop. Ative-a aqui para criar uma configuração predefinida.',
  'mobile.mirrorSettingsWebcamSent': 'As alterações são guardadas no desktop e valem a partir da próxima música.',
  'mobile.mirrorLoadError': 'Não foi possível carregar os dados.',
  'mobile.mirrorRetry': 'Tentar novamente',
  'mobile.mirrorNoProfileLink': 'Nenhum perfil vinculado. Ligue a app Companion a um perfil para ver seus dados.',
  'mobile.mirrorProfileMissing': 'Seu perfil não foi encontrado no desktop. Suas conquistas aparecerão aqui assim que o perfil do desktop sincronizar.',
  'mobile.mirrorOnlyMine': 'Apenas minhas',
  'mobile.mirrorAll': 'Todas',
  'mobile.mirrorEntries': '{n} entradas',
  'mobile.mirrorDailyNoData': 'Sem dados diários para o seu perfil.',
  'mobile.mirrorDailyControlHint': 'Apenas visualização — assuma o controle para iniciar desafios.',
  'mobile.mirrorDailyModesHint': 'Os modos de desafio são jogados no desktop — isto é o catálogo.',
  'mobile.mirrorSlotsToday': '{n}/{m} lugares hoje',
  'mobile.mirrorPlayer': 'Jogador',
  'mobile.mirrorProfileYou': 'Você',
  'mobile.mirrorProfileControlHint': 'Apenas visualização — assuma o controle para ativar ou desativar perfis.',
  'mobile.mirrorSongsShort': 'Músicas',
  'mobile.mirrorJukeboxFilters': 'Filtros',
  'mobile.mirrorJukeboxFilterSet': 'Definir filtros',
  'mobile.mirrorJukeboxFilterRemove': 'Remover filtro',
  'mobile.mirrorJukeboxNoFilters': 'Nenhum filtro ativo — a Jukebox toca de todo o repertório.',
  'mobile.mirrorJukeboxFilterGenre': 'Gênero',
  'mobile.mirrorJukeboxFilterArtist': 'Artista',
  'mobile.mirrorJukeboxFilterEra': 'Década',
  'mobile.mirrorJukeboxFilterYear': 'Ano',
  'mobile.mirrorJukeboxFilterAllArtists': 'Todos os artistas',
  'mobile.mirrorJukeboxFilterAllEras': 'Todas as décadas',
  'mobile.mirrorJukeboxFilterAllYears': 'Todos os anos',
  'mobile.mirrorJukeboxFilterApplied': 'Filtro definido — surte efeito no desktop.',
  'mobile.mirrorJukeboxFilterCleared': 'Filtro removido.',
  'mobile.mirrorJukeboxNoLibrary': 'Carregando biblioteca…',
  'mobile.mirrorJukeboxStateChipPool': 'Repertório',
  'mobile.mirrorJukeboxPoolAll': 'Todas as músicas',
  'mobile.mirrorJukeboxPlaylistsTitle': 'Playlists e repertório',
  'mobile.mirrorJukeboxPlaylistSongs': '{n} músicas',
  'mobile.mirrorJukeboxSystemBadge': 'Sistema',
  'mobile.mirrorJukeboxSetPool': 'Definir como repertório',
  'mobile.mirrorJukeboxActivePool': 'Repertório ativo',
  'mobile.mirrorJukeboxPoolSet': 'Repertório de músicas definido.',
  'mobile.mirrorJukeboxPoolCleared': 'Repertório redefinido — todas as músicas.',
  'mobile.mirrorJukeboxEnqueue': 'Para a lista de desejos',
  'mobile.mirrorJukeboxEnqueueConfirm': 'Colocar na fila?',
  'mobile.mirrorJukeboxEnqueued': 'Playlist na fila — toca no desktop em breve.',
  'mobile.mirrorJukeboxPlaylistsEmpty': 'Ainda não há playlists.',
  'mobile.mirrorJukeboxPlaylistsError': 'Não foi possível carregar as playlists.',
  'mobile.mirrorJukeboxRefresh': 'Atualizar',
  'mobile.mirrorJukeboxRequestedBy': 'por',
  'mobile.mirrorQueueEmptyTitle': 'Ainda não há pedidos',
  'mobile.mirrorQueueEmptyBrowse': 'Explore a biblioteca e escolha uma música!',
  'mobile.mirrorQueueDesktopControls': 'O desktop decide quando se canta',
  'mobile.queueSlotsFull': 'Todos os lugares ocupados',
  'mobile.hotkeys.cardTitle': 'Atalhos de teclado',
  'mobile.hotkeys.cardHint': 'Os atalhos mais importantes para o desktop',
  'mobile.hotkeys.collapse': 'Recolher atalhos de teclado',
  'mobile.hotkeys.expand': 'Expandir atalhos de teclado',
  'mobile.hotkeys.esc': 'Pausa / voltar / cancelar',
  'mobile.hotkeys.enter': 'Retomar (em pausa)',
  'mobile.hotkeys.f12': 'Ativar/desativar tela cheia',
  'mobile.hotkeys.ctrlL': 'Focar a pesquisa da biblioteca',
  'mobile.hotkeys.ctrlR': 'Música aleatória (solo)',
  'mobile.hotkeys.ctrlD': 'Música aleatória (duelo)',
  'mobile.hotkeys.ctrlQ': 'Tocar a próxima música da fila',
  'mobile.hotkeys.ctrlJ': 'Abrir a Jukebox',
  'mobile.hotkeys.fkeys': 'Ir direto às telas: F1 Início · F2 Biblioteca · F3 Festa · F4 Fila · F5 Perfis · F6 Pontuações · F7 Conquistas · F8 Jukebox · F9 Configurações · F10 Editor',
  'mobileHelp.title': 'Ajuda',
  'mobileHelp.close': 'Fechar',
  'mobileHelp.intro': 'App Companion: tudo sobre conexão, controle remoto, participação e canto — em cinco capítulos curtos.',
  'mobileHelp.ch1Title': 'Conexão e microfone',
  'mobileHelp.ch1b1': 'Escaneie o QR code no desktop ou abra o link Companion — telefone e PC precisam estar na mesma rede WiFi.',
  'mobileHelp.ch1b2': 'Crie um perfil (nome, cor, foto) — ele sincroniza automaticamente com o desktop.',
  'mobileHelp.ch1b3': 'Na primeira vez que você canta, o navegador pede acesso ao microfone — toque em "Permitir".',
  'mobileHelp.ch1b4': 'O código no canto superior direito do cabeçalho mostra que a conexão está ativa.',
  'mobileHelp.ch2Title': 'Controle remoto: assumir o controle',
  'mobileHelp.ch2b1': 'Com "Assumir controle", seu telefone espelha a tela do desktop — você sempre vê o que roda no PC.',
  'mobileHelp.ch2b2': 'Sua barra de abas então comanda o desktop: início, biblioteca, festa, fila, Jukebox, pontuações, conquistas, definições.',
  'mobileHelp.ch2b3': 'Na página inicial você pode pausar ou pular a música atual.',
  'mobileHelp.ch2b4': 'Somente UM dispositivo controla por vez — "Liberar controle" abre a vaga.',
  'mobileHelp.ch3Title': 'Sem controle',
  'mobileHelp.ch3b1': 'Pedir músicas: abra a biblioteca, toque numa música, escolha as opções (modo, dificuldade, micro) e adicione à fila — até 3 músicas.',
  'mobileHelp.ch3b2': 'Chat: toque em 💬 no canto superior direito e converse com o anfitrião e os outros jogadores.',
  'mobileHelp.ch3b3': 'Festa: você vota nas escolhas de músicas, vê os sinais de vez e canta quando chega sua vez — tudo por overlays, sem precisar de controle.',
  'mobileHelp.ch3b4': 'Suas próprias conquistas e pontuações ficam na barra de abas (🏅 conquistas, 🏆 pontuações).',
  'mobileHelp.ch3b5': 'Áreas com cadeado (definições, perfis, festa, desafio, Jukebox) precisam de controle remoto — seu próprio perfil você sempre pode editar.',
  'mobileHelp.ch4Title': 'Cantando com o telefone',
  'mobileHelp.ch4b1': 'Quando chega a sua vez no jogo, o microfone inicia automaticamente — no Battle Royale todos cantam ao mesmo tempo.',
  'mobileHelp.ch4b2': 'A barra fina abaixo do cabeçalho mostra o volume e a nota detectada do seu canto.',
  'mobileHelp.ch4b3': 'Segure o telefone perto da boca e mantenha a música do alto-falante longe do aparelho.',
  'mobileHelp.ch5Title': 'Solução de problemas',
  'mobileHelp.ch5b1': 'Conexão perdida: a app reconecta automaticamente. Caso contrário, verifique a WiFi e toque em "Tentar Conexão Novamente".',
  'mobileHelp.ch5b2': 'Sem microfone/som: verifique a permissão do microfone nas configurações do site no navegador.',
  'mobileHelp.ch5b3': 'Espelho fica vazio: o desktop (app do PC) precisa estar em execução e na mesma rede.',
  'mobileHelp.ch5b4': 'Controle não responde: outro aparelho está com o controle — o cartão de status na página inicial mostra quem controla.',
  'mobileHelp.localOnlyNote': 'Esta ajuda roda inteiramente no seu telefone — ela não controla o desktop.',
  'mobileViews.desktopDefaultDifficulty': 'Padrão do desktop',
  'mobileViews.queueAddAction': 'Adicionar à Fila',
  'settings.loudnessNormalization': 'Normalização de volume (alvo de 89 dB)',
  'tutorial.companion.chapters.control': 'Controle remoto: Take Control',
  'tutorial.companion.chapters.solo': 'Sem controle',
  'tutorial.companion.chapters.help': 'Ajuda do Companion',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': 'Um telefone agora só comanda o desktop sob comando: o botão "Assumir controle" no Companion pega o controle remoto — antes e depois disso, o telefone toca apenas para si.',
  'tutorial.companion.steps.takeControl.details': 'O mecanismo por trás de "Assumir controle":\n• O controle é reservado exclusivamente para exatamente um aparelho (bloqueio remoto).\n• Desktop e telefone que controla ficam em sincronia: cada lado vê na hora o que o outro faz.\n• Todos os demais telefones mostram o status "Controlado por …" e aguardam.\n\nO controle termina com "Libertar" — ou automaticamente quando o telefone perde a conexão.',
  'tutorial.companion.steps.controlSync.title': 'Desktop e telefone em sincronia',
  'tutorial.companion.steps.controlSync.body': 'De volta à aba Móvel: aqui você vê, como anfitrião, todos os aparelhos. Quando um telefone assume o controle, ele espelha a tela do desktop e opera telas, botões e confirmações — mouse e teclado no desktop continuam totalmente utilizáveis.',
  'tutorial.companion.steps.controlSync.details': 'Como os dois lados rodam em sincronia, ninguém consegue "tocar e fugir": clique no desktop e o telefone que controla acompanha — toque no telefone e o desktop troca de tela.\n\nNa lista de aparelhos você reconhece o aparelho que controla pelo badge de controle remoto.',
  'tutorial.companion.steps.controlHandover.title': 'Só um controle remoto por vez',
  'tutorial.companion.steps.controlHandover.body': 'O controle é exclusivo: enquanto um telefone comanda, nenhum segundo assume — o botão dele mostra em vez disso quem está no controle. Libertar ou desconectar devolve o controle na hora.',
  'tutorial.companion.steps.controlHandover.details': 'Bom saber:\n• O anfitrião pode continuar clicando a qualquer momento — o telefone que controla acompanha (e mantém o controle).\n• Se o telefone que controla perder a conexão (bateria, WiFi), o controle volta automaticamente ao desktop.\n• Uma expulsão da lista de aparelhos também encerra o controle.',
  'tutorial.companion.steps.soloOverview.title': 'Convidados sem controle 🙋',
  'tutorial.companion.steps.soloOverview.body': 'A maioria dos convidados nunca precisa do controle remoto: telefones conectados sem Take Control são acompanhantes autônomos — pedem músicas, conversam no chat, cantam junto e conferem as próprias conquistas sem tocar no desktop.',
  'tutorial.companion.steps.soloOverview.details': 'O que os telefones sem controle podem fazer:\n• 🎵 Colocar as próprias músicas na fila (com o distintivo 📱)\n• 💬 Entrar no chat da festa\n• 🎤 Cantar nos modos de festa (Companion Sing-A-Long, Passe o Microfone)\n• 🗳️ Votar nas enquetes (torneio, Battle Royale)\n• 🏆 Ver as próprias pontuações e conquistas',
  'tutorial.companion.steps.soloQueue.title': 'Pedidos sem controle',
  'tutorial.companion.steps.soloQueue.body': 'Mesmo sem controle remoto, cada convidado enfileira as próprias músicas: escolha uma música no telefone, coloque na fila — pronto. O pedido chega aqui com o distintivo 📱 e conta para o limite de 3 músicas do perfil.',
  'tutorial.companion.steps.soloParty.title': 'Cantar junto e votar',
  'tutorial.companion.steps.soloParty.body': 'A participação na festa passa sempre pelos telefones: no Companion Sing-A-Long e no Passe o Microfone os convidados cantam direto do aparelho, no torneio e no Battle Royale votam com um toque — tudo sem Take Control.',
  'tutorial.companion.steps.soloStats.title': 'Conquistas e pontuações próprias',
  'tutorial.companion.steps.soloStats.body': 'Cada convidado mantém seu próprio álbum: no telefone dá para ver as próprias pontuações e conquistas — sem Take Control. O que o perfil conquista, o convidado confere até do sofá.',
  'tutorial.companion.steps.soloLimits.title': 'O que segue bloqueado',
  'tutorial.companion.steps.soloLimits.body': 'Sem controle, definições, perfis, configuração da festa, desafios diários e Jukebox ficam de fora — seguem reservados ao desktop (ou a um Companion com Take Control).',
  'tutorial.companion.steps.soloLimits.details': 'Por que o cadeado? Essas áreas mudam o estado do jogo ou a configuração para todos: definições, gestão de perfis, configuração da festa, desafios diários e Jukebox. É para isso que existe o controle explícito — "Assumir controle" desbloqueia para exatamente um telefone.\n\nO anfitrião do desktop sempre mantém tudo em suas mãos.',
  'tutorial.companion.steps.helpButton.title': 'Ajuda em cada telefone ❓',
  'tutorial.companion.steps.helpButton.body': 'Você conhece o menu ? aqui na barra de menu — cada telefone conectado ganha seu próprio botão "?". Um toque abre a ajuda do Companion direto no aparelho.',
  'tutorial.companion.steps.helpLocal.title': 'Só ler, nunca controlar',
  'tutorial.companion.steps.helpLocal.body': 'A ajuda do Companion é uma visualização somente leitura: ela não envia comandos ao desktop e nunca inicia um tour do desktop. Os convidados podem abri-la a qualquer momento — mesmo enquanto alguém canta ou controla.',
  'tutorial.companion.steps.helpLocal.details': 'Assim a ajuda fica deliberadamente separada do sistema de controle: um convidado que só quer consultar algo ("Como coloco uma música na fila?") não exerce nenhuma influência sobre a noite em andamento — e os tours aqui no desktop continuam assunto do anfitrião.\n\nAbra pelo botão "?" na app Companion; feche simplesmente fechando a visualização.',
}

# ─────────────────────────────── 日本語 (敬体) ───────────────────────────────
T['ja'] = {
  'mobile.toastControlAcquired': '操作を取得しました',
  'mobile.toastControlReleased': '操作を解放しました',
  'mobile.toastControlLost': '操作が失われました',
  'mobile.toastControlTaken': '操作はすでに取得されています',
  'mobile.toastLockedNav': 'リモート操作が必要です',
  'mobile.homeControlYouTitle': 'あなたがデスクトップを操作中',
  'mobile.homeControlYouDesc': 'あなたのタブがデスクトップを操作します — すべてのエリアが開放されています。',
  'mobile.homeCurrentSong': '現在の曲',
  'mobile.homeHotkeysTitle': 'デスクトップのショートカットキー',
  'mobile.homeHotkeysDesc': 'デスクトップの重要なショートカット',
  'mobile.homeRequestSong': '曲をリクエスト',
  'mobile.homeTakeControlForFull': '操作を取得してフルアクセス',
  'mobile.homeControlByTitle': '操作は{name}が保持中',
  'mobile.homeControlFreeTitle': '誰も操作していません',
  'mobile.homeControlHintDesc': '操作なしでも、曲のリクエスト、チャット、参加ができます。',
  'mobile.mirrorSettingsSubtitle': 'スマホからデスクトップの設定をリアルタイムに操作',
  'mobile.mirrorSettingsNoSnapshot': 'デスクトップの値をまだ受信していません — 既定値を表示中',
  'mobile.mirrorSettingsNeedControl': 'デスクトップに変更を送るにはリモート操作を取得してください',
  'mobile.mirrorSettingsWebcamNone': 'デスクトップではまだウェブカメラが設定されていません。ここで有効化すると既定の設定が作成されます。',
  'mobile.mirrorSettingsWebcamSent': '変更はデスクトップに保存され、次の曲から有効になります。',
  'mobile.mirrorLoadError': 'データを読み込めませんでした。',
  'mobile.mirrorRetry': '再試行',
  'mobile.mirrorNoProfileLink': 'プロフィールが未リンクです。コンパニオンアプリをプロフィールに接続するとデータが表示されます。',
  'mobile.mirrorProfileMissing': 'プロフィールがデスクトップで見つかりませんでした。デスクトップのプロフィールが同期されると、実績がここに表示されます。',
  'mobile.mirrorOnlyMine': '自分のみ',
  'mobile.mirrorAll': 'すべて',
  'mobile.mirrorEntries': '{n}件',
  'mobile.mirrorDailyNoData': 'このプロフィールのデイリーデータはありません。',
  'mobile.mirrorDailyControlHint': '表示のみ — チャレンジを開始するには操作を取得してください。',
  'mobile.mirrorDailyModesHint': 'チャレンジモードはデスクトップでプレイします — ここはカタログです。',
  'mobile.mirrorSlotsToday': '今日のスロット {n}/{m}',
  'mobile.mirrorPlayer': 'プレイヤー',
  'mobile.mirrorProfileYou': 'あなた',
  'mobile.mirrorProfileControlHint': '表示のみ — プロフィールの有効化/無効化には操作を取得してください。',
  'mobile.mirrorSongsShort': '曲',
  'mobile.mirrorJukeboxFilters': 'フィルター',
  'mobile.mirrorJukeboxFilterSet': 'フィルターを設定',
  'mobile.mirrorJukeboxFilterRemove': 'フィルターを解除',
  'mobile.mirrorJukeboxNoFilters': 'フィルターなし — ジュークボックスは全プールから再生します。',
  'mobile.mirrorJukeboxFilterGenre': 'ジャンル',
  'mobile.mirrorJukeboxFilterArtist': 'アーティスト',
  'mobile.mirrorJukeboxFilterEra': '年代',
  'mobile.mirrorJukeboxFilterYear': '年',
  'mobile.mirrorJukeboxFilterAllArtists': 'すべてのアーティスト',
  'mobile.mirrorJukeboxFilterAllEras': 'すべての年代',
  'mobile.mirrorJukeboxFilterAllYears': 'すべての年',
  'mobile.mirrorJukeboxFilterApplied': 'フィルターを設定しました — デスクトップに反映されます。',
  'mobile.mirrorJukeboxFilterCleared': 'フィルターを解除しました。',
  'mobile.mirrorJukeboxNoLibrary': 'ライブラリを読み込み中…',
  'mobile.mirrorJukeboxStateChipPool': 'プール',
  'mobile.mirrorJukeboxPoolAll': 'すべての曲',
  'mobile.mirrorJukeboxPlaylistsTitle': 'プレイリストとプール',
  'mobile.mirrorJukeboxPlaylistSongs': '{n}曲',
  'mobile.mirrorJukeboxSystemBadge': 'システム',
  'mobile.mirrorJukeboxSetPool': 'プールに設定',
  'mobile.mirrorJukeboxActivePool': '現在のプール',
  'mobile.mirrorJukeboxPoolSet': '楽曲プールを設定しました。',
  'mobile.mirrorJukeboxPoolCleared': '楽曲プールをリセットしました — すべての曲。',
  'mobile.mirrorJukeboxEnqueue': 'お気に入りへ',
  'mobile.mirrorJukeboxEnqueueConfirm': 'キューに入れますか？',
  'mobile.mirrorJukeboxEnqueued': 'プレイリストをキューに追加しました — まもなくデスクトップで再生されます。',
  'mobile.mirrorJukeboxPlaylistsEmpty': 'プレイリストはまだありません。',
  'mobile.mirrorJukeboxPlaylistsError': 'プレイリストを読み込めませんでした。',
  'mobile.mirrorJukeboxRefresh': '更新',
  'mobile.mirrorJukeboxRequestedBy': 'リクエスト:',
  'mobile.mirrorQueueEmptyTitle': 'リクエストはまだありません',
  'mobile.mirrorQueueEmptyBrowse': 'ライブラリから曲を選ぼう！',
  'mobile.mirrorQueueDesktopControls': '歌うタイミングはデスクトップが決めます',
  'mobile.queueSlotsFull': 'すべての枠が埋まっています',
  'mobile.hotkeys.cardTitle': 'キーボードショートカット',
  'mobile.hotkeys.cardHint': 'デスクトップの主要なショートカット',
  'mobile.hotkeys.collapse': 'ショートカットを折りたたむ',
  'mobile.hotkeys.expand': 'ショートカットを展開する',
  'mobile.hotkeys.esc': '一時停止 / 戻る / キャンセル',
  'mobile.hotkeys.enter': '再開（一時停止中）',
  'mobile.hotkeys.f12': '全画面表示の切り替え',
  'mobile.hotkeys.ctrlL': 'ライブラリ検索にフォーカス',
  'mobile.hotkeys.ctrlR': 'ランダム曲（ソロ）',
  'mobile.hotkeys.ctrlD': 'ランダム曲（デュエル）',
  'mobile.hotkeys.ctrlQ': 'キューの次の曲を再生',
  'mobile.hotkeys.ctrlJ': 'ジュークボックスを開く',
  'mobile.hotkeys.fkeys': '画面へ直接ジャンプ：F1 ホーム · F2 ライブラリ · F3 パーティー · F4 キュー · F5 プロフィール · F6 ハイスコア · F7 実績 · F8 ジュークボックス · F9 設定 · F10 エディター',
  'mobileHelp.title': 'ヘルプ',
  'mobileHelp.close': '閉じる',
  'mobileHelp.intro': 'コンパニオンアプリ：接続、リモート操作、参加、歌唱のすべて — 5つの短いチャプターでご紹介します。',
  'mobileHelp.ch1Title': '接続とマイク',
  'mobileHelp.ch1b1': 'デスクトップのQRコードをスキャンするか、コンパニオンのリンクを開いてください — スマホとPCは同じWiFiネットワークにいる必要があります。',
  'mobileHelp.ch1b2': 'プロフィール（名前・色・写真）を作成しましょう — デスクトップと自動的に同期されます。',
  'mobileHelp.ch1b3': '初めて歌うとき、ブラウザがマイクへのアクセスを求めます — 「許可」をタップしてください。',
  'mobileHelp.ch1b4': 'ヘッダー右上のコードは、接続が確立していることを示します。',
  'mobileHelp.ch2Title': 'リモート操作：操作を取得',
  'mobileHelp.ch2b1': '「操作を取得」でスマホにデスクトップ画面が映し出されます — PCで動いているものを常に確認できます。',
  'mobileHelp.ch2b2': 'タブバーでそのままデスクトップを操作できます：ホーム、ライブラリ、パーティー、キュー、ジュークボックス、ハイスコア、実績、設定。',
  'mobileHelp.ch2b3': 'ホームページから現在の曲の一時停止やスキップができます。',
  'mobileHelp.ch2b4': '同時に操作できるのは1台だけ — 「操作を解除」で枠が空きます。',
  'mobileHelp.ch3Title': '操作なしで',
  'mobileHelp.ch3b1': '曲のリクエスト：ライブラリを開き、曲をタップしてオプション（モード・難易度・マイク）を選び、キューに追加 — 最大3曲まで。',
  'mobileHelp.ch3b2': 'チャット：右上の💬をタップして、ホストや他のプレイヤーと話せます。',
  'mobileHelp.ch3b3': 'パーティー：曲の投票に参加し、順番の合図を確認し、自分の番に歌います — すべてオーバーレイ経由で、操作は不要です。',
  'mobileHelp.ch3b4': '自分の実績とハイスコアはタブバーにあります（🏅 実績、🏆 ハイスコア）。',
  'mobileHelp.ch3b5': '鍵のかかったエリア（設定、プロフィール、パーティー、チャレンジ、ジュークボックス）にはリモート操作が必要です — 自分のプロフィールはいつでも編集できます。',
  'mobileHelp.ch4Title': 'スマホで歌う',
  'mobileHelp.ch4b1': 'ゲームで自分の番が来るとマイクは自動的に起動します — バトルロイヤルでは全員が同時に歌います。',
  'mobileHelp.ch4b2': 'ヘッダーの下の細いバーに、音量と検出された音程が表示されます。',
  'mobileHelp.ch4b3': 'スマホを口に近づけ、スピーカーの音楽を端末から遠ざけましょう。',
  'mobileHelp.ch5Title': 'トラブルシューティング',
  'mobileHelp.ch5b1': '接続が切れた：アプリは自動的に再接続します。それでもつながらない場合はWiFiを確認し、「再接続」をタップしてください。',
  'mobileHelp.ch5b2': 'マイク/音が出ない：ブラウザのサイト設定でマイクの権限を確認してください。',
  'mobileHelp.ch5b3': 'ミラーが空のまま：デスクトップ（PCアプリ）が起動していて、同じネットワークにいる必要があります。',
  'mobileHelp.ch5b4': '操作が反応しない：別の端末が操作中です — ホームページのステータスカードに、誰が操作しているかが表示されます。',
  'mobileHelp.localOnlyNote': 'このヘルプは完全にスマホ上で動作します — デスクトップは操作しません。',
  'mobileViews.desktopDefaultDifficulty': 'デスクトップの既定値',
  'mobileViews.queueAddAction': 'キューに追加',
  'settings.loudnessNormalization': '音量のノーマライズ（89 dB目標）',
  'tutorial.companion.chapters.control': 'リモート操作：Take Control',
  'tutorial.companion.chapters.solo': '操作なしで',
  'tutorial.companion.chapters.help': 'コンパニオンのヘルプ',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': 'スマホがデスクトップを操作するのは、これからは指示を受けたときだけ：コンパニオンの「操作を取得」ボタンがリモコンを手に入れます — その前後は、スマホは自分のためにだけタップします。',
  'tutorial.companion.steps.takeControl.details': '「操作を取得」の仕組み：\n• 操作は正確に1台の端末だけに排他的に予約されます（リモートロック）。\n• デスクトップと操作中のスマホは同期し続けます：お互いが相手の操作を即座に確認できます。\n• その他のスマホには「…が操作中」というステータスが表示され、待機します。\n\n操作は「解放」で終了 — またはスマホが接続を失うと自動的に終了します。',
  'tutorial.companion.steps.controlSync.title': 'デスクトップとスマホの同期',
  'tutorial.companion.steps.controlSync.body': 'モバイルタブに戻ります：ホストとして、ここで全端末を確認できます。スマホが操作を取得すると、デスクトップ画面をミラーし、画面・ボタン・確認ダイアログを操作します — デスクトップのマウスとキーボードは引き続き完全に使えます。',
  'tutorial.companion.steps.controlSync.details': '両側が同期して動くため、誰も「先にタップして逃げる」ことはできません：デスクトップでクリックすれば操作中のスマホが追従し — スマホでタップすればデスクトップが画面を切り替えます。\n\n端末リストでは、リモコンバッジで操作中の端末を見分けられます。',
  'tutorial.companion.steps.controlHandover.title': 'リモコンは同時に1つだけ',
  'tutorial.companion.steps.controlHandover.body': '操作は排他的です：1台のスマホが操作している間、2台目は取得できません — そのボタンには代わりに、誰が操作中かが表示されます。解放や切断で、操作は即座に空きます。',
  'tutorial.companion.steps.controlHandover.details': '知っておくと便利：\n• ホストはいつでも自分でクリックし続けられます — 操作中のスマホが追従します（操作も保持されます）。\n• 操作中のスマホが接続を失うと（バッテリー、WiFi）、操作は自動的にデスクトップへ戻ります。\n• 端末リストからキックしても操作は終了します。',
  'tutorial.companion.steps.soloOverview.title': '操作を持たないゲスト 🙋',
  'tutorial.companion.steps.soloOverview.body': 'ほとんどのゲストはリモコンを必要としません：Take Controlなしで接続されたスマホは、自立したコンパニオンです — 曲をリクエストし、チャットし、歌に参加し、自分の実績を確認します。デスクトップに触れることなく。',
  'tutorial.companion.steps.soloOverview.details': '操作を持たないスマホにできること：\n• 🎵 自分の曲をキューに入れる（📱バッジ付き）\n• 💬 パーティーチャットに参加\n• 🎤 パーティーモードで歌う（コンパニオン・シング・アロング、マイクパス）\n• 🗳️ 投票に参加（トーナメント、バトルロイヤル）\n• 🏆 自分のハイスコアと実績を見る',
  'tutorial.companion.steps.soloQueue.title': '操作なしのリクエスト',
  'tutorial.companion.steps.soloQueue.body': 'リモコンがなくても、すべてのゲストが自分の曲をキューに入れられます：スマホで曲を選び、キューに入れる — それだけ。リクエストは📱バッジ付きでここに届き、プロフィールの3曲制限にカウントされます。',
  'tutorial.companion.steps.soloParty.title': '一緒に歌う＆投票',
  'tutorial.companion.steps.soloParty.body': 'パーティーへの参加は常にスマホ経由です：コンパニオン・シング・アロングとマイクパスではゲストが端末から直接歌い、トーナメントとバトルロイヤルではタップで投票します — すべてTake Controlなしで。',
  'tutorial.companion.steps.soloStats.title': '自分の実績とハイスコア',
  'tutorial.companion.steps.soloStats.body': 'すべてのゲストが自分のアルバムを持っています：スマホでは自分のハイスコアと実績を確認できます — Take Controlは不要です。プロフィールが獲得したものは、ソファからでも確認できます。',
  'tutorial.companion.steps.soloLimits.title': 'ロックされたままのもの',
  'tutorial.companion.steps.soloLimits.body': '操作なしでは、設定、プロフィール、パーティー設定、デイリーチャレンジ、ジュークボックスは使えません — デスクトップ（またはTake Control中のコンパニオン）のために予約されたままです。',
  'tutorial.companion.steps.soloLimits.details': 'なぜロック？ これらのエリアは全員のゲーム状態や設定を変更します：設定、プロフィール管理、パーティー設定、デイリーチャレンジ、ジュークボックス。そのために明示的な操作があります — 「操作を取得」は正確に1台のスマホだけのためにそれらを解放します。\n\nデスクトップのホストは、常にすべてを自分の手の中に持っています。',
  'tutorial.companion.steps.helpButton.title': 'すべてのスマホにヘルプ ❓',
  'tutorial.companion.steps.helpButton.body': 'メニューバーの？メニューはご存じですね — 接続されたすべてのスマホには、それぞれの「？」ボタンが付きます。タップ一回で、端末上で直接コンパニオンヘルプが開きます。',
  'tutorial.companion.steps.helpLocal.title': '読み取り専用、操作はしない',
  'tutorial.companion.steps.helpLocal.body': 'コンパニオンヘルプは純粋な閲覧ビューです：デスクトップにコマンドを送らず、デスクトップのツアーを開始することもありません。ゲストはいつでも開けます — 誰かが歌ったり操作したりしている間でも。',
  'tutorial.companion.steps.helpLocal.details': 'ヘルプは意図的に操作システムから切り離されています：何かを調べたいだけのゲスト（「曲をキューに入れるには？」）は、今夜の進行にまったく影響を与えません — そしてここのデスクトップのツアーは、ホストであるあなたのものです。\n\nコンパニオンアプリの「？」ボタンから開き、ビューを閉じるだけで終了します。',
}

# ─────────────────────────────── 한국어 (해요/합니다) ───────────────────────────────
T['ko'] = {
  'mobile.toastControlAcquired': '제어권을 가져왔어요',
  'mobile.toastControlReleased': '제어를 해제했어요',
  'mobile.toastControlLost': '제어를 잃었어요',
  'mobile.toastControlTaken': '이미 다른 기기가 제어 중이에요',
  'mobile.toastLockedNav': '원격 제어가 필요해요',
  'mobile.homeControlYouTitle': '내가 데스크톱을 제어 중',
  'mobile.homeControlYouDesc': '내 탭이 데스크톱을 움직여요 — 모든 영역이 열려 있어요.',
  'mobile.homeCurrentSong': '현재 곡',
  'mobile.homeHotkeysTitle': '데스크톱 단축키',
  'mobile.homeHotkeysDesc': '데스크톱의 가장 중요한 단축키',
  'mobile.homeRequestSong': '곡 요청하기',
  'mobile.homeTakeControlForFull': '모든 기능을 쓰려면 제어권 가져오기',
  'mobile.homeControlByTitle': '{name}이(가) 제어 중',
  'mobile.homeControlFreeTitle': '제어 중인 기기 없음',
  'mobile.homeControlHintDesc': '제어 없이도 곡을 요청하고, 채팅하고, 참여할 수 있어요.',
  'mobile.mirrorSettingsSubtitle': '휴대폰에서 데스크톱 설정을 실시간으로 제어',
  'mobile.mirrorSettingsNoSnapshot': '데스크톱 값을 아직 받지 못했어요 — 기본값을 표시하는 중',
  'mobile.mirrorSettingsNeedControl': '변경을 데스크톱으로 보내려면 원격 제어를 가져오세요',
  'mobile.mirrorSettingsWebcamNone': '데스크톱에 아직 웹캠이 설정되어 있지 않아요. 여기서 활성화하면 기본 설정이 생성됩니다.',
  'mobile.mirrorSettingsWebcamSent': '변경 사항은 데스크톱에 저장되고 다음 곡부터 적용됩니다.',
  'mobile.mirrorLoadError': '데이터를 불러오지 못했어요.',
  'mobile.mirrorRetry': '다시 시도',
  'mobile.mirrorNoProfileLink': '연결된 프로필이 없어요. 컴패니언 앱을 프로필에 연결하면 내 데이터를 볼 수 있어요.',
  'mobile.mirrorProfileMissing': '데스크톱에서 프로필을 찾지 못했어요. 데스크톱 프로필이 동기화되면 업적이 여기 표시됩니다.',
  'mobile.mirrorOnlyMine': '내 것만',
  'mobile.mirrorAll': '전체',
  'mobile.mirrorEntries': '{n}개 항목',
  'mobile.mirrorDailyNoData': '이 프로필의 데일리 데이터가 없어요.',
  'mobile.mirrorDailyControlHint': '보기 전용 — 챌린지를 시작하려면 제어권을 가져오세요.',
  'mobile.mirrorDailyModesHint': '챌린지 모드는 데스크톱에서 플레이해요 — 여기는 카탈로그입니다.',
  'mobile.mirrorSlotsToday': '오늘의 슬롯 {n}/{m}',
  'mobile.mirrorPlayer': '플레이어',
  'mobile.mirrorProfileYou': '나',
  'mobile.mirrorProfileControlHint': '보기 전용 — 프로필을 켜거나 끄려면 제어권을 가져오세요.',
  'mobile.mirrorSongsShort': '곡',
  'mobile.mirrorJukeboxFilters': '필터',
  'mobile.mirrorJukeboxFilterSet': '필터 설정',
  'mobile.mirrorJukeboxFilterRemove': '필터 제거',
  'mobile.mirrorJukeboxNoFilters': '활성 필터 없음 — 주크박스가 전체 곡 풀에서 재생해요.',
  'mobile.mirrorJukeboxFilterGenre': '장르',
  'mobile.mirrorJukeboxFilterArtist': '아티스트',
  'mobile.mirrorJukeboxFilterEra': '연대',
  'mobile.mirrorJukeboxFilterYear': '연도',
  'mobile.mirrorJukeboxFilterAllArtists': '전체 아티스트',
  'mobile.mirrorJukeboxFilterAllEras': '전체 연대',
  'mobile.mirrorJukeboxFilterAllYears': '전체 연도',
  'mobile.mirrorJukeboxFilterApplied': '필터가 설정됐어요 — 데스크톱에 적용됩니다.',
  'mobile.mirrorJukeboxFilterCleared': '필터를 제거했어요.',
  'mobile.mirrorJukeboxNoLibrary': '라이브러리 불러오는 중…',
  'mobile.mirrorJukeboxStateChipPool': '풀',
  'mobile.mirrorJukeboxPoolAll': '전체 곡',
  'mobile.mirrorJukeboxPlaylistsTitle': '플레이리스트와 풀',
  'mobile.mirrorJukeboxPlaylistSongs': '{n}곡',
  'mobile.mirrorJukeboxSystemBadge': '시스템',
  'mobile.mirrorJukeboxSetPool': '풀로 설정',
  'mobile.mirrorJukeboxActivePool': '현재 풀',
  'mobile.mirrorJukeboxPoolSet': '곡 풀을 설정했어요.',
  'mobile.mirrorJukeboxPoolCleared': '곡 풀을 초기화했어요 — 전체 곡.',
  'mobile.mirrorJukeboxEnqueue': '위시리스트로',
  'mobile.mirrorJukeboxEnqueueConfirm': '대기열에 추가할까요?',
  'mobile.mirrorJukeboxEnqueued': '플레이리스트를 대기열에 넣었어요 — 곧 데스크톱에서 재생됩니다.',
  'mobile.mirrorJukeboxPlaylistsEmpty': '아직 플레이리스트가 없어요.',
  'mobile.mirrorJukeboxPlaylistsError': '플레이리스트를 불러오지 못했어요.',
  'mobile.mirrorJukeboxRefresh': '새로고침',
  'mobile.mirrorJukeboxRequestedBy': '요청:',
  'mobile.mirrorQueueEmptyTitle': '아직 요청이 없어요',
  'mobile.mirrorQueueEmptyBrowse': '라이브러리에서 곡을 골라 보세요!',
  'mobile.mirrorQueueDesktopControls': '언제 부를지는 데스크톱이 정해요',
  'mobile.queueSlotsFull': '모든 자리가 찼어요',
  'mobile.hotkeys.cardTitle': '키보드 단축키',
  'mobile.hotkeys.cardHint': '데스크톱 필수 단축키',
  'mobile.hotkeys.collapse': '단축키 접기',
  'mobile.hotkeys.expand': '단축키 펼치기',
  'mobile.hotkeys.esc': '일시정지 / 뒤로 / 취소',
  'mobile.hotkeys.enter': '재개 (일시정지 중)',
  'mobile.hotkeys.f12': '전체 화면 켜기/끄기',
  'mobile.hotkeys.ctrlL': '라이브러리 검색으로 이동',
  'mobile.hotkeys.ctrlR': '랜덤 곡 (솔로)',
  'mobile.hotkeys.ctrlD': '랜덤 곡 (듀얼)',
  'mobile.hotkeys.ctrlQ': '대기열의 다음 곡 재생',
  'mobile.hotkeys.ctrlJ': '주크박스 열기',
  'mobile.hotkeys.fkeys': '화면으로 바로 이동: F1 홈 · F2 라이브러리 · F3 파티 · F4 대기열 · F5 프로필 · F6 최고 점수 · F7 업적 · F8 주크박스 · F9 설정 · F10 에디터',
  'mobileHelp.title': '도움말',
  'mobileHelp.close': '닫기',
  'mobileHelp.intro': '컴패니언 앱: 연결, 원격 제어, 참여, 노래에 관한 모든 것 — 다섯 개의 짧은 장에서 소개해요.',
  'mobileHelp.ch1Title': '연결과 마이크',
  'mobileHelp.ch1b1': '데스크톱의 QR 코드를 스캔하거나 컴패니언 링크를 여세요 — 휴대폰과 PC가 같은 WiFi 네트워크에 있어야 해요.',
  'mobileHelp.ch1b2': '프로필(이름, 색상, 사진)을 만들면 데스크톱과 자동으로 동기화돼요.',
  'mobileHelp.ch1b3': '처음 노래할 때 브라우저가 마이크 권한을 물어봐요 — "허용"을 눌러주세요.',
  'mobileHelp.ch1b4': '헤더 오른쪽 위의 코드는 연결이 살아 있다는 표시예요.',
  'mobileHelp.ch2Title': '원격 제어: 제어권 가져오기',
  'mobileHelp.ch2b1': '"제어권 가져오기"를 누르면 휴대폰에 데스크톱 화면이 그대로 비쳐요 — PC에서 뭘 하는지 항상 보여요.',
  'mobileHelp.ch2b2': '그러면 내 탭 바가 데스크톱을 움직여요: 홈, 라이브러리, 파티, 대기열, 주크박스, 최고 점수, 업적, 설정.',
  'mobileHelp.ch2b3': '홈 화면에서 지금 곡을 일시정지하거나 건너뛸 수 있어요.',
  'mobileHelp.ch2b4': '동시에 제어할 수 있는 기기는 하나뿐 — "해제"가 자리를 열어줘요.',
  'mobileHelp.ch3Title': '제어 없이',
  'mobileHelp.ch3b1': '곡 요청: 라이브러리를 열고 곡을 탭한 뒤 옵션(모드, 난이도, 마이크)을 고르고 대기열에 넣어요 — 최대 3곡까지.',
  'mobileHelp.ch3b2': '채팅: 오른쪽 위의 💬를 눌러 진행자와 다른 플레이어에게 말을 걸어보세요.',
  'mobileHelp.ch3b3': '파티: 곡 투표에 투표하고, 차례 알림을 확인하고, 내 차례에 노래해요 — 전부 오버레이로, 제어 없이도 가능해요.',
  'mobileHelp.ch3b4': '내 업적과 최고 점수는 탭 바에서 볼 수 있어요 (🏅 업적, 🏆 최고 점수).',
  'mobileHelp.ch3b5': '자물쇠가 걸린 영역(설정, 프로필, 파티, 챌린지, 주크박스)은 원격 제어가 필요해요 — 내 프로필은 언제든 수정할 수 있어요.',
  'mobileHelp.ch4Title': '휴대폰으로 노래하기',
  'mobileHelp.ch4b1': '게임에서 내 차례가 되면 마이크가 자동으로 켜져요 — 배틀로얄에서는 모두가 동시에 불러요.',
  'mobileHelp.ch4b2': '헤더 아래의 얇은 바가 내 목소리의 볼륨과 감지된 음을 보여줘요.',
  'mobileHelp.ch4b3': '휴대폰을 입에 가까이 대고, 스피커 음악은 기기에서 멀리 떨어뜨리세요.',
  'mobileHelp.ch5Title': '문제 해결',
  'mobileHelp.ch5b1': '연결 끊김: 앱이 자동으로 다시 연결해요. 그래도 안 되면 WiFi를 확인하고 "연결 재시도"를 눌러주세요.',
  'mobileHelp.ch5b2': '마이크/소리 없음: 브라우저의 사이트 설정에서 마이크 권한을 확인하세요.',
  'mobileHelp.ch5b3': '미러가 비어 있어요: 데스크톱(PC 앱)이 실행 중이고 같은 네트워크에 있어야 해요.',
  'mobileHelp.ch5b4': '제어가 반응하지 않아요: 다른 기기가 제어 중이에요 — 홈 화면의 상태 카드에 누가 제어 중인지 표시됩니다.',
  'mobileHelp.localOnlyNote': '이 도움말은 휴대폰에서만 완전히 실행돼요 — 데스크톱을 제어하지 않습니다.',
  'mobileViews.desktopDefaultDifficulty': '데스크톱 기본값',
  'mobileViews.queueAddAction': '대기열에 추가',
  'settings.loudnessNormalization': '음량 정규화 (89 dB 목표)',
  'tutorial.companion.chapters.control': '원격 제어: Take Control',
  'tutorial.companion.chapters.solo': '제어 없이',
  'tutorial.companion.chapters.help': '컴패니언 도움말',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': '이제 휴대폰은 명령이 있을 때만 데스크톱을 움직여요: 컴패니언의 "제어권 가져오기" 버튼이 리모컨을 가져오는 거예요 — 그 전후로는 휴대폰이 자기 자신을 위해서만 탭해요.',
  'tutorial.companion.steps.takeControl.details': '"제어권 가져오기"의 원리:\n• 제어는 정확히 한 대의 기기에만 배타적으로 예약돼요(원격 잠금).\n• 데스크톱과 제어 중인 휴대폰은 동기화를 유지해요: 서로가 무엇을 하는지 즉시 보입니다.\n• 나머지 휴대폰은 "…이(가) 제어 중" 상태를 보며 기다려요.\n\n제어는 "해제"로 끝나요 — 휴대폰이 연결을 잃으면 자동으로 끝나기도 합니다.',
  'tutorial.companion.steps.controlSync.title': '데스크톱과 휴대폰의 동기화',
  'tutorial.companion.steps.controlSync.body': '모바일 탭으로 돌아와서: 진행자로서 여기서 모든 기기를 볼 수 있어요. 휴대폰이 제어권을 가져오면 데스크톱 화면을 미러링하고 화면, 버튼, 확인 창을 조작해요 — 데스크톱의 마우스와 키보드는 계속 완전히 쓸 수 있어요.',
  'tutorial.companion.steps.controlSync.details': '양쪽이 동기화되어 돌아가기 때문에 아무도 "먼저 탭하고 도망"갈 수 없어요: 데스크톱에서 클릭하면 제어 중인 휴대폰이 따라가고 — 휴대폰에서 탭하면 데스크톱이 화면을 바꿔요.\n\n기기 목록에서는 리모컨 배지로 제어 중인 기기를 알아볼 수 있어요.',
  'tutorial.companion.steps.controlHandover.title': '리모컨은 한 번에 하나만',
  'tutorial.companion.steps.controlHandover.body': '제어는 배타적이에요: 한 휴대폰이 조작하는 동안 두 번째 휴대폰은 가져올 수 없어요 — 그 버튼에는 대신 누가 제어 중인지 표시됩니다. 해제하거나 연결이 끊기면 제어는 즉시 풀려요.',
  'tutorial.companion.steps.controlHandover.details': '알아두면 좋아요:\n• 진행자는 언제든 직접 클릭할 수 있어요 — 제어 중인 휴대폰이 따라가요(제어도 유지됩니다).\n• 제어 중인 휴대폰이 연결을 잃으면(배터리, WiFi) 제어는 자동으로 데스크톱으로 돌아가요.\n• 기기 목록에서 추방해도 제어가 끝나요.',
  'tutorial.companion.steps.soloOverview.title': '제어 없는 손님 🙋',
  'tutorial.companion.steps.soloOverview.body': '대부분의 손님은 리모컨이 필요 없어요: Take Control 없이 연결된 휴대폰은 독립적인 컴패니언이에요 — 곡을 요청하고, 채팅하고, 같이 부르고, 데스크톱을 건드리지 않고 자기 업적을 확인해요.',
  'tutorial.companion.steps.soloOverview.details': '제어 없는 휴대폰이 할 수 있는 것:\n• 🎵 자기 곡을 대기열에 넣기 (📱 배지 표시)\n• 💬 파티 채팅 참여\n• 🎤 파티 모드에서 노래하기 (컴패니언 싱얼롱, 마이크 넘기기)\n• 🗳️ 투표하기 (토너먼트, 배틀로얄)\n• 🏆 자기 최고 점수와 업적 보기',
  'tutorial.companion.steps.soloQueue.title': '제어 없이 요청하기',
  'tutorial.companion.steps.soloQueue.body': '리모컨이 없어도 모든 손님이 자기 곡을 대기열에 넣을 수 있어요: 휴대폰에서 곡을 고르고, 넣으면 — 끝. 요청은 📱 배지와 함께 여기 도착하고 프로필의 3곡 제한에 포함돼요.',
  'tutorial.companion.steps.soloParty.title': '함께 노래하고 투표하기',
  'tutorial.companion.steps.soloParty.body': '파티 참여는 언제나 휴대폰을 통해 이뤄져요: 컴패니언 싱얼롱과 마이크 넘기기에서는 손님이 자기 기기로 바로 부르고, 토너먼트와 배틀로얄에서는 탭으로 투표해요 — 전부 Take Control 없이.',
  'tutorial.companion.steps.soloStats.title': '내 업적과 최고 점수',
  'tutorial.companion.steps.soloStats.body': '모든 손님은 자기 앨범을 가지고 있어요: 휴대폰에서 자기 최고 점수와 업적을 볼 수 있어요 — Take Control이 필요 없어요. 프로필이 얻은 건 소파에 앉아서도 확인할 수 있죠.',
  'tutorial.companion.steps.soloLimits.title': '잠금으로 남는 것들',
  'tutorial.companion.steps.soloLimits.body': '제어가 없으면 설정, 프로필, 파티 구성, 일일 챌린지, 주크박스는 쓸 수 없어요 — 데스크톱(또는 Take Control 중인 컴패니언) 전용으로 남습니다.',
  'tutorial.companion.steps.soloLimits.details': '왜 잠길까요? 이 영역은 모두의 게임 상태나 설정을 바꿔요: 설정, 프로필 관리, 파티 구성, 일일 챌린지, 주크박스. 그래서 명시적인 제어가 있는 거예요 — "제어권 가져오기"가 정확히 한 대의 휴대폰을 위해 잠금을 풀어줘요.\n\n데스크톱 진행자는 언제나 모든 걸 직접 손에 쥐고 있어요.',
  'tutorial.companion.steps.helpButton.title': '모든 휴대폰에 도움말 ❓',
  'tutorial.companion.steps.helpButton.body': '메뉴 바의 ? 메뉴는 아시죠 — 연결된 모든 휴대폰에 자기만의 "?" 버튼이 생겨요. 한 번 탭하면 기기에서 바로 컴패니언 도움말이 열립니다.',
  'tutorial.companion.steps.helpLocal.title': '읽기만 하고, 제어는 안 해요',
  'tutorial.companion.steps.helpLocal.body': '컴패니언 도움말은 순수한 읽기 전용 화면이에요: 데스크톱에 명령을 보내지 않고 데스크톱 투어를 시작하는 일도 없어요. 손님들은 언제든 열 수 있어요 — 누가 노래하거나 제어하는 중에도요.',
  'tutorial.companion.steps.helpLocal.details': '이렇게 도움말은 의도적으로 제어 시스템과 분리돼 있어요: 그냥 뭘 좀 찾아보려는 손님("곡을 대기열에 넣으려면?")은 진행 중인 파티에 아무 영향도 주지 않아요 — 그리고 데스크톱의 투어는 진행자인 당신의 몫으로 남죠.\n\n컴패니언 앱의 "?" 버튼으로 열고, 화면을 닫는 것으로 끝내면 돼요.',
}

# ─────────────────────────────── 简体中文 (你) ───────────────────────────────
T['zh'] = {
  'mobile.toastControlAcquired': '已获取控制权',
  'mobile.toastControlReleased': '已释放控制',
  'mobile.toastControlLost': '控制已丢失',
  'mobile.toastControlTaken': '控制权已被占用',
  'mobile.toastLockedNav': '仅限远程控制',
  'mobile.homeControlYouTitle': '你正在控制桌面端',
  'mobile.homeControlYouDesc': '你的标签页驱动桌面端——所有区域都已解锁。',
  'mobile.homeCurrentSong': '当前歌曲',
  'mobile.homeHotkeysTitle': '桌面端快捷键',
  'mobile.homeHotkeysDesc': '桌面端最重要的快捷键',
  'mobile.homeRequestSong': '点一首歌',
  'mobile.homeTakeControlForFull': '获取控制权以使用全部功能',
  'mobile.homeControlByTitle': '控制权在 {name} 手中',
  'mobile.homeControlFreeTitle': '当前无人控制',
  'mobile.homeControlHintDesc': '不控制也能点歌、聊天和参与。',
  'mobile.mirrorSettingsSubtitle': '用手机实时控制桌面端设置',
  'mobile.mirrorSettingsNoSnapshot': '尚未收到桌面端的数值——当前显示默认值',
  'mobile.mirrorSettingsNeedControl': '获取远程控制后才能把更改发送到桌面端',
  'mobile.mirrorSettingsWebcamNone': '桌面端尚未设置摄像头。在此启用即可创建默认配置。',
  'mobile.mirrorSettingsWebcamSent': '更改将保存到桌面端，并从下一首歌开始生效。',
  'mobile.mirrorLoadError': '无法加载数据。',
  'mobile.mirrorRetry': '重试',
  'mobile.mirrorNoProfileLink': '未关联档案。请将伴侣应用连接到一个档案以查看你的数据。',
  'mobile.mirrorProfileMissing': '在桌面端没有找到你的档案。桌面端档案同步后，你的成就会显示在这里。',
  'mobile.mirrorOnlyMine': '仅我的',
  'mobile.mirrorAll': '全部',
  'mobile.mirrorEntries': '{n} 条记录',
  'mobile.mirrorDailyNoData': '你的档案暂无每日数据。',
  'mobile.mirrorDailyControlHint': '仅查看——获取控制权后才能开始挑战。',
  'mobile.mirrorDailyModesHint': '挑战模式在桌面端进行——这里只是目录。',
  'mobile.mirrorSlotsToday': '今日名额 {n}/{m}',
  'mobile.mirrorPlayer': '玩家',
  'mobile.mirrorProfileYou': '你',
  'mobile.mirrorProfileControlHint': '仅查看——获取控制权后才能启用或停用档案。',
  'mobile.mirrorSongsShort': '歌曲',
  'mobile.mirrorJukeboxFilters': '筛选',
  'mobile.mirrorJukeboxFilterSet': '设置筛选',
  'mobile.mirrorJukeboxFilterRemove': '移除筛选',
  'mobile.mirrorJukeboxNoFilters': '当前没有筛选——点唱机会从整个歌池中播放。',
  'mobile.mirrorJukeboxFilterGenre': '风格',
  'mobile.mirrorJukeboxFilterArtist': '歌手',
  'mobile.mirrorJukeboxFilterEra': '年代',
  'mobile.mirrorJukeboxFilterYear': '年份',
  'mobile.mirrorJukeboxFilterAllArtists': '所有歌手',
  'mobile.mirrorJukeboxFilterAllEras': '所有年代',
  'mobile.mirrorJukeboxFilterAllYears': '所有年份',
  'mobile.mirrorJukeboxFilterApplied': '筛选已设置——将在桌面端生效。',
  'mobile.mirrorJukeboxFilterCleared': '筛选已移除。',
  'mobile.mirrorJukeboxNoLibrary': '正在加载曲库…',
  'mobile.mirrorJukeboxStateChipPool': '歌池',
  'mobile.mirrorJukeboxPoolAll': '全部歌曲',
  'mobile.mirrorJukeboxPlaylistsTitle': '播放列表与歌池',
  'mobile.mirrorJukeboxPlaylistSongs': '{n} 首歌',
  'mobile.mirrorJukeboxSystemBadge': '系统',
  'mobile.mirrorJukeboxSetPool': '设为歌池',
  'mobile.mirrorJukeboxActivePool': '当前歌池',
  'mobile.mirrorJukeboxPoolSet': '已设置歌池。',
  'mobile.mirrorJukeboxPoolCleared': '已重置歌池——包含全部歌曲。',
  'mobile.mirrorJukeboxEnqueue': '加入心愿单',
  'mobile.mirrorJukeboxEnqueueConfirm': '加入队列？',
  'mobile.mirrorJukeboxEnqueued': '播放列表已排入队列——很快会在桌面端播放。',
  'mobile.mirrorJukeboxPlaylistsEmpty': '还没有播放列表。',
  'mobile.mirrorJukeboxPlaylistsError': '无法加载播放列表。',
  'mobile.mirrorJukeboxRefresh': '刷新',
  'mobile.mirrorJukeboxRequestedBy': '来自',
  'mobile.mirrorQueueEmptyTitle': '还没有点歌',
  'mobile.mirrorQueueEmptyBrowse': '去曲库挑一首歌吧！',
  'mobile.mirrorQueueDesktopControls': '何时开唱由桌面端决定',
  'mobile.queueSlotsFull': '所有名额已满',
  'mobile.hotkeys.cardTitle': '键盘快捷键',
  'mobile.hotkeys.cardHint': '桌面端常用快捷键一览',
  'mobile.hotkeys.collapse': '收起快捷键',
  'mobile.hotkeys.expand': '展开快捷键',
  'mobile.hotkeys.esc': '暂停 / 返回 / 取消',
  'mobile.hotkeys.enter': '继续（暂停时）',
  'mobile.hotkeys.f12': '切换全屏',
  'mobile.hotkeys.ctrlL': '聚焦曲库搜索',
  'mobile.hotkeys.ctrlR': '随机歌曲（单人）',
  'mobile.hotkeys.ctrlD': '随机歌曲（对决）',
  'mobile.hotkeys.ctrlQ': '播放队列中的下一首',
  'mobile.hotkeys.ctrlJ': '打开点唱机',
  'mobile.hotkeys.fkeys': '直达各个画面：F1 主页 · F2 曲库 · F3 派对 · F4 队列 · F5 档案 · F6 高分榜 · F7 成就 · F8 点唱机 · F9 设置 · F10 编辑器',
  'mobileHelp.title': '帮助',
  'mobileHelp.close': '关闭',
  'mobileHelp.intro': '伴侣应用：关于连接、远程控制、参与和演唱的一切——分五个简短章节。',
  'mobileHelp.ch1Title': '连接与麦克风',
  'mobileHelp.ch1b1': '扫描桌面端的二维码，或打开伴侣应用链接——手机和电脑必须在同一个 WiFi 网络中。',
  'mobileHelp.ch1b2': '创建一个档案（姓名、颜色、照片）——它会自动与桌面端同步。',
  'mobileHelp.ch1b3': '第一次演唱时，浏览器会请求麦克风权限——请点"允许"。',
  'mobileHelp.ch1b4': '页眉右上角的代码表示连接已建立。',
  'mobileHelp.ch2Title': '远程控制：接管控制',
  'mobileHelp.ch2b1': '点击"获取控制权"后，手机会镜像桌面端画面——你随时能看到电脑上正在播放什么。',
  'mobileHelp.ch2b2': '随后你的标签栏就会驱动桌面端：主页、曲库、派对、队列、点唱机、高分榜、成就、设置。',
  'mobileHelp.ch2b3': '在主页上可以暂停或跳过当前歌曲。',
  'mobileHelp.ch2b4': '同一时间只有一台设备可以控制——"释放控制"会腾出位置。',
  'mobileHelp.ch3Title': '不进行控制',
  'mobileHelp.ch3b1': '点歌：打开曲库，点一首歌，选择选项（模式、难度、麦克风），加入队列——最多 3 首。',
  'mobileHelp.ch3b2': '聊天：点右上角的 💬，与主持人和其他玩家交流。',
  'mobileHelp.ch3b3': '派对：你可以在歌曲投票中投票，看到轮次提示，轮到你时就一起唱——全部通过浮层完成，不需要控制。',
  'mobileHelp.ch3b4': '你自己的成就和高分在标签栏里（🏅 成就、🏆 高分榜）。',
  'mobileHelp.ch3b5': '带锁的区域（设置、档案、派对、挑战、点唱机）需要远程控制——你自己的档案随时可以编辑。',
  'mobileHelp.ch4Title': '用手机演唱',
  'mobileHelp.ch4b1': '轮到你演唱时，麦克风会自动开启——大逃杀模式下所有人同时演唱。',
  'mobileHelp.ch4b2': '页眉下方的细条会显示你歌声的音量和检测到的音符。',
  'mobileHelp.ch4b3': '把手机靠近嘴边，并让扬声器的音乐远离设备。',
  'mobileHelp.ch5Title': '故障排除',
  'mobileHelp.ch5b1': '连接断开：应用会自动重连。如果不行，请检查 WiFi 并点"重新连接"。',
  'mobileHelp.ch5b2': '没有麦克风/声音：在浏览器的站点设置中检查麦克风权限。',
  'mobileHelp.ch5b3': '镜像一直空白：桌面端（PC 应用）必须正在运行且处于同一网络。',
  'mobileHelp.ch5b4': '控制没反应：其他设备正持有控制权——主页上的状态卡片会显示谁在控制。',
  'mobileHelp.localOnlyNote': '这份帮助完全在你的手机上运行——它不会控制桌面端。',
  'mobileViews.desktopDefaultDifficulty': '桌面端默认',
  'mobileViews.queueAddAction': '加入队列',
  'settings.loudnessNormalization': '音量标准化（89 dB 目标）',
  'tutorial.companion.chapters.control': '远程控制：Take Control',
  'tutorial.companion.chapters.solo': '不进行控制',
  'tutorial.companion.chapters.help': '伴侣应用帮助',
  'tutorial.companion.steps.takeControl.title': 'Take Control 🎮',
  'tutorial.companion.steps.takeControl.body': '现在，手机只有在接到指令时才会驱动桌面端：伴侣应用上的"获取控制权"按钮会取得遥控器——在此之前和之后，手机只为自己点按。',
  'tutorial.companion.steps.takeControl.details': '"获取控制权"背后的机制：\n• 控制权仅排他性地保留给唯一一台设备（远程锁定）。\n• 桌面端与控制中的手机保持同步：双方都能立即看到对方的操作。\n• 其余手机会显示"由 … 控制"的状态并等待。\n\n控制通过"释放"结束——手机失去连接时也会自动结束。',
  'tutorial.companion.steps.controlSync.title': '桌面端与手机同步运行',
  'tutorial.companion.steps.controlSync.body': '回到"移动端"标签页：作为主持人，你可以在这里看到所有设备。手机接管控制后，会镜像桌面端画面并操作页面、按钮和确认框——桌面端的鼠标和键盘仍可完全使用。',
  'tutorial.companion.steps.controlSync.details': '由于两侧同步运行，谁也无法"抢先点走"：你在桌面端点击，控制中的手机就会跟随——你在手机上点按，桌面端就会切换画面。\n\n在设备列表中，你可以通过遥控徽章认出正在控制的设备。',
  'tutorial.companion.steps.controlHandover.title': '同一时间只有一只遥控器',
  'tutorial.companion.steps.controlHandover.body': '控制权是独占的：一台手机控制时，第二台无法接管——它的按钮会改为显示谁在控制。释放或断开连接会立即让出控制权。',
  'tutorial.companion.steps.controlHandover.details': '小提示：\n• 主持人随时可以自己继续点击——控制中的手机会跟随（并保留控制权）。\n• 如果控制中的手机失去连接（电量、WiFi），控制权会自动回到桌面端。\n• 从设备列表中踢出设备也会结束控制。',
  'tutorial.companion.steps.soloOverview.title': '没有控制权的客人 🙋',
  'tutorial.companion.steps.soloOverview.body': '大多数客人根本用不到遥控器：未取得 Take Control 的已连接手机是独立的伴侣设备——它们点歌、聊天、跟唱并查看自己的成就，完全不碰桌面端。',
  'tutorial.companion.steps.soloOverview.details': '没有控制权的手机能做什么：\n• 🎵 把自己的歌排入队列（带 📱 徽章）\n• 💬 加入派对聊天\n• 🎤 在派对模式中演唱（手机伴唱、传麦克风）\n• 🗳️ 在投票中投票（锦标赛、大逃杀）\n• 🏆 查看自己的高分和成就',
  'tutorial.companion.steps.soloQueue.title': '无控制权的点歌',
  'tutorial.companion.steps.soloQueue.body': '即使没有遥控器，每位客人也能排入自己的歌：在手机上选一首歌，排进队列——完成。请求会带 📱 徽章出现在这里，并计入档案的 3 首上限。',
  'tutorial.companion.steps.soloParty.title': '跟唱与投票',
  'tutorial.companion.steps.soloParty.body': '派对参与始终通过手机进行：在手机伴唱和传麦克风中，客人直接用自己的设备演唱；在锦标赛和大逃杀中，他们点按投票——全部无需 Take Control。',
  'tutorial.companion.steps.soloStats.title': '自己的成就与高分',
  'tutorial.companion.steps.soloStats.body': '每位客人都有自己的收藏册：在手机上可以查看自己的高分和成就——无需 Take Control。档案赢得的一切，客人坐在沙发上也能查看。',
  'tutorial.companion.steps.soloLimits.title': '仍然锁定的内容',
  'tutorial.companion.steps.soloLimits.body': '没有控制权时，设置、档案、派对配置、每日挑战和点唱机仍然不可用——它们保留给桌面端（或取得 Take Control 的伴侣）。',
  'tutorial.companion.steps.soloLimits.details': '为什么要锁定？这些区域会改变所有人的游戏状态或配置：设置、档案管理、派对配置、每日挑战和点唱机。这正是显式控制的意义——"获取控制权"只为唯一一台手机解锁它们。\n\n桌面端主持人始终把一切掌握在自己手中。',
  'tutorial.companion.steps.helpButton.title': '每部手机上都有帮助 ❓',
  'tutorial.companion.steps.helpButton.body': '你知道菜单栏里的 ? 菜单——每部已连接的手机都会获得自己的"？"按钮。点一下就会直接在设备上打开伴侣帮助。',
  'tutorial.companion.steps.helpLocal.title': '只读，绝不控制',
  'tutorial.companion.steps.helpLocal.body': '伴侣帮助是纯阅读视图：它不会向桌面端发送任何命令，也绝不会启动桌面端导览。客人可以随时打开——即使有人正在演唱或控制。',
  'tutorial.companion.steps.helpLocal.details': '这样，帮助就与控制系统刻意分开：只想查点东西的客人（"怎么把歌排进队列？"）不会对进行中的夜晚产生任何影响——而桌面端上的这些导览仍归你这位主持人所有。\n\n通过伴侣应用中的"？"按钮打开；直接关闭视图即可退出。',
}

# ════════════════════════════ EINFÜGE-LOGIK ════════════════════════════

def js_str(s: str) -> str:
    out = s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n').replace('\r', '')
    return f"'{out}'"

def read(p):
    with open(p, encoding='utf-8') as f:
        return f.read()

def write(p, src):
    with open(p, 'w', encoding='utf-8') as f:
        f.write(src)

def insert_after_blank(src, pattern, block):
    """Nach der gematchten Zeile einfügen + Leerzeile (wie en/de merge-script). Tail bleibt."""
    m = re.search(pattern, src, re.M)
    if not m:
        raise RuntimeError(f'pattern not found: {pattern}')
    return src[:m.end()] + '\n' + block + '\n' + src[m.end():]

def insert_after_tight(src, pattern, block):
    """Nach der gematchten Zeile einfügen, KEINE Leerzeile (für tutorial, wie en/de hand-ediert)."""
    m = re.search(pattern, src, re.M)
    if not m:
        raise RuntimeError(f'pattern not found: {pattern}')
    return src[:m.end()] + '\n' + block + src[m.end():]

def insert_before_tight(src, pattern, block):
    """Vor der gematchten Zeile einfügen, KEINE Leerzeile."""
    m = re.search(pattern, src, re.M)
    if not m:
        raise RuntimeError(f'pattern not found: {pattern}')
    return src[:m.start()] + block + '\n' + src[m.start():]

def key_line_count(src, key):
    return len(re.findall(rf'^[ \t]*{re.escape(key)}\s*:', src, re.M))

def companion_section(src):
    """Spanne des companion-Abschnitts in tutorial.ts zurückgeben."""
    m = re.search(r'^    companion: \{', src, re.M)
    if not m:
        raise RuntimeError('companion section not found')
    m2 = re.search(r'^    \},\s*$', src[m.end():], re.M)
    end = m.end() + (m2.start() if m2 else len(src) - m.end())
    return m.start(), end

# ── Sanity: Übersetzungs-Deckelung ──
expected = set(ALL_KEYS)
for lang in LANGS:
    missing = expected - set(T[lang])
    extra = set(T[lang]) - expected
    if missing or extra:
        sys.exit(f'T[{lang}] inkomplett: missing={sorted(missing)} extra={sorted(extra)}')
print(f'Übersetzungen OK: 7 Sprachen × {len(expected)} Keys')

report = {}
for lang in LANGS:
    r = dict(flat=0, hotkeys=0, help=0, views=0, settings=0, tut_ch=0, tut_steps=0)
    mobile_p = f'{BASE}/{lang}/mobile.ts'
    settings_p = f'{BASE}/{lang}/settings.ts'
    tutorial_p = f'{BASE}/{lang}/tutorial.ts'

    # ── mobile.ts ──
    src = read(mobile_p)

    # 1) flache Keys + hotkeys nach `mobile: {`
    todo_flat = [k for k in FLAT if key_line_count(src, leaf(k)) == 0]
    partial_flat = [k for k in FLAT if key_line_count(src, leaf(k)) > 1]
    if partial_flat:
        sys.exit(f'{lang}: doppelte mobile-Keys: {partial_flat}')
    todo_hk = [k for k in HOTKEYS if key_line_count(src, leaf(k)) == 0]
    if todo_flat or todo_hk:
        parts = ['// ── R33: Companion-Neubau (P1-P19) ──']
        parts += [f'  {leaf(k)}: {js_str(T[lang][k])},' for k in todo_flat]
        if todo_hk:
            parts.append('// ── R33-e (P3): Hotkeys-Karte (Desktop-Home + Companion-Startseite) ──')
            parts.append('  hotkeys: {')
            parts += [f'    {leaf(k)}: {js_str(T[lang][k])},' for k in todo_hk]
            parts.append('  },')
        src = insert_after_blank(src, r'^mobile: \{', '\n'.join(parts))
        r['flat'] = len(todo_flat)
        r['hotkeys'] = len(todo_hk)

    # 2) mobileHelp nach export const mobileTranslations = {
    if not re.search(r'^mobileHelp: \{', src, re.M):
        parts = ['// ── R33/P19: Companion-Hilfe-View (rein lokal, keine Desktop-Befehle) ──',
                 'mobileHelp: {']
        parts += [f'  {leaf(k)}: {js_str(T[lang][k])},' for k in HELP]
        parts.append('},')
        src = insert_after_blank(src, r'^export const mobileTranslations = \{', '\n'.join(parts))
        r['help'] = len(HELP)

    # 3) mobileViews
    todo_v = [k for k in VIEWS if key_line_count(src, leaf(k)) == 0]
    if todo_v:
        parts = ['// ── R33: Companion-Neubau ──'] + [f'  {leaf(k)}: {js_str(T[lang][k])},' for k in todo_v]
        src = insert_after_blank(src, r'^mobileViews: \{', '\n'.join(parts))
        r['views'] = len(todo_v)

    write(mobile_p, src)

    # ── settings.ts ──
    src = read(settings_p)
    if key_line_count(src, 'loudnessNormalization') == 0:
        parts = ['// ── R33/P5: Loudness-Normalisierung (89 dB Ziel) ──',
                 f'  loudnessNormalization: {js_str(T[lang]["settings.loudnessNormalization"])},']
        src = insert_after_blank(src, r'^settings: \{', '\n'.join(parts))
        write(settings_p, src)
        r['settings'] = 1

    # ── tutorial.ts ──
    src = read(tutorial_p)
    c_start, c_end = companion_section(src)
    section = src[c_start:c_end]

    # 4) chapters: control/solo/help nach `features:` (Reihenfolge wie en/de)
    todo_ch = [k for k in TUT_CH if key_line_count(section, leaf(k)) == 0]
    if todo_ch:
        fm = re.search(r'^([ \t]*)features: .*$', section, re.M)
        if not fm:
            sys.exit(f'{lang}: features-Zeile im companion-Abschnitt nicht gefunden')
        indent = fm.group(1)
        ch_block = '\n'.join(f'{indent}{leaf(k)}: {js_str(T[lang][k])},' for k in todo_ch)
        abs_pos = c_start + fm.end()
        src = src[:abs_pos] + '\n' + ch_block + src[abs_pos:]
        r['tut_ch'] = len(todo_ch)
        # Spanne nach dieser Einfügung aktualisieren
        c_start, c_end = companion_section(src)
        section = src[c_start:c_end]

    # 5) Steps zwischen singAlong und deviceList (Reihenfolge wie r33-e/en/de)
    todo_steps = [s for s in STEPS_ORDER
                  if not re.search(rf'^([ \t]*){s}: \{{', section, re.M)]
    if todo_steps:
        dm = re.search(r'^([ \t]*)deviceList: \{', section, re.M)
        if not dm:
            sys.exit(f'{lang}: deviceList im companion-Abschnitt nicht gefunden')
        s_indent = dm.group(1)          # 8 Spaces
        f_indent = s_indent + '  '      # 10 Spaces
        lines = []
        for s in todo_steps:
            lines.append(f'{s_indent}{s}: {{')
            for field in ('title', 'body', 'details'):
                k = f'tutorial.companion.steps.{s}.{field}'
                if k in T[lang]:
                    lines.append(f'{f_indent}{field}: {js_str(T[lang][k])},')
            lines.append(f'{s_indent}}},')
        steps_block = '\n'.join(lines)
        abs_pos = c_start + dm.start()
        src = src[:abs_pos] + steps_block + '\n' + src[abs_pos:]
        r['tut_steps'] = sum(1 for s in todo_steps for f in ('title', 'body', 'details')
                             if f'tutorial.companion.steps.{s}.{f}' in T[lang])

    write(tutorial_p, src)
    report[lang] = r
    print(f'— {lang}: mobile-flat={r["flat"]} hotkeys={r["hotkeys"]} mobileHelp={r["help"]} '
          f'mobileViews={r["views"]} settings={r["settings"]} tutorial-chapters={r["tut_ch"]} '
          f'tutorial-step-fields={r["tut_steps"]}')

total = sum(sum(r.values()) for r in report.values())
print(f'done — insgesamt {total} Key-Einfügungen über 7 Sprachen (Soll: 7×143=1001, '
      f'wenn alle Blöcke frisch eingefügt wurden)')
